### ISSUE TITLE
Complex search query returns empty result set

### ISSUE THREAD

**Issue by lemsergey** [spotify/web-api#103]
It seems that Web API search feature is broken.

Here you can see simple requests, which cannot return empty sets.
<https://developer.spotify.com/web-api/console/get-search-item?q=artist%3Aplacebo%2Balbum%3Ameds&type=album>
<https://developer.spotify.com/web-api/console/get-search-item?q=album%3Aabsolution%2Bartist%3Amuse&type=album>

Complex request, which specifies artist and album always return empty set.
Simple requests works without problems, but I am using Spotify API to find particular album of the artist and some keywords return many results. I can parse this results to find out necessary album, but Web API docs offers subject way.

**Comment by thelinmichael** [comment]
Hi @lemsergey! Thanks for bringing this up. The search is actually not broken, but the API Console has a behaviour that may be unexpected. If you use a `+` sign, the API Console encodes it to an actual plus, `%2B, in your Web API query, instead of `%20` that a browser would if you used `+` in the URL bar.

`GET /v1/search?q=album%3Aabsolution%2Bartist%3Amuse&type=album` returns nothing.

`GET /v1/search?q=album%3Aabsolution+artist%3Amuse&type=album HTTP/1.1` returns the results you're expecting. When using the API Console, use a space character instead of `+`. 

I revised the documentation last time this came up, and I'll do the same again to see if this could be clarified somewhat or if we should simply change the behaviour of the Console.

**Comment by lemsergey** [comment]
Thank you for response.
This API is quite confusing in this case. 
Using it from Obj-C code with AFNetworking i found out that I need to replace '+' with simple space character, and this is a little bit confusing, especially when artist or album name has its own space in the name.
