### ISSUE TITLE
Add an offset-based pagination to the followed artists endpoint

### ISSUE THREAD

**Issue by khamaileon** [spotify/web-api#104]
The cursor-based pagination does not allow concurrent requests due to the fact that information about the next set of items is in the response itself. An offset-based pagination would be more suitable.

**Comment by thelinmichael** [comment]
@khamaileon, this is a great point and you could argue it'd been optimal for both the way applications consume the API, and for API consistency. However, due to technical limitations in the way that followed artists are handled internally, offset-based paging wasn't possible and won't be for the foreseeable future.
