### ISSUE TITLE
Audio Analysis for a Track returns 504 frequently

### ISSUE THREAD

**Issue by kannnnn** [spotify/web-api#1057]
Issue found on 18 Oct 2018

#### Endpoint(s):
* `https://api.spotify.com/v1/audio-analysis/{id}`

#### Scope(s):
* None 

#### Steps to reproduce:
1. Call the 'audio-analysis' endpoint with any track id and oAuth Token

This has been tested using curl, in the web API console or in code and found the same results.

#### Expected behaviour:
Server returns: 200 OK
A public track analysis object as described on `https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/`.

#### Actual behaviour:
504 Service didn't reply before timeout is occurring roughly 80% of the time.  20% of the time the response works correctly.

<img width="610" alt="screen shot 2018-10-18 at 13 53 11" src="https://user-images.githubusercontent.com/32287842/47128514-34308300-d2dd-11e8-98ed-f4865731a509.png">

**Comment by arirawr** [comment]
Hey @kannnnn - I haven't been able to reproduce this. Could you let me know a track ID for which this happens consistently?

**Comment by theunixbeard** [comment]
@arirawr I think I know the issue --- in the Spotify docs for this API route there is a sample Track ID:

https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/

`3JIxjvbbDrA9ztYlNcp3yL`

Turns out that one always times out (not sure if it is real, or was removed, etc)

<img width="1336" alt="screen shot 2019-02-21 at 6 42 58 pm" src="https://user-images.githubusercontent.com/892435/53166717-aeb13c80-3608-11e9-9708-3f5a3f0d7bc1.png">

<img width="934" alt="screen shot 2019-02-21 at 6 44 59 pm" src="https://user-images.githubusercontent.com/892435/53166771-ce486500-3608-11e9-93af-48e5e1116f01.png">

So if anything, perhaps the docs should be updated to have a different track ID in the sample cURL command.

**Comment by prinsherbert** [comment]
I consistently have the same error when trying to play a track using the website (so not the API), in the development console I found this request resulted in a 504:

    fetch("https://gew-spclient.spotify.com/track-playback/v1/devices", {
    "headers": {
        "accept": "*/*",
        "accept-language": "en-US,en;q=0.9,nl;q=0.8",
        "authorization": "Bearer  ...",
        "cache-control": "no-cache",
        "content-type": "application/json",
        "pragma": "no-cache",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site"
    },
    "referrerPolicy": "no-referrer-when-downgrade",
    "body": "{\"device\":{\"brand\":\"spotify\",\"capabilities\":{\"change_volume\":true,\"audio_podcasts\":true,\"enable_play_token\":true,\"play_token_lost_behavior\":\"pause\",\"disable_connect\":false,\"video_playback\":true,\"manifest_formats\":[\"file_urls_mp3\",\"file_urls_external\",\"file_ids_mp4\",\"file_ids_mp4_dual\",\"manifest_ids_video\"]},\"device_id\":\" .... \",\"device_type\":\"computer\",\"metadata\":{},\"model\":\"web_player\",\"name\":\"Web Player (Chrome)\",\"platform_identifier\":\"web_player linux undefined;chrome 81.0.4044.113;desktop\"},\"connection_id\":\" ... ",\"client_version\":\"harmony:4.2.0-6f9b9aa\",\"volume\":65535}",
    "method": "POST",
    "mode": "cors"
    });

Returned:

    {
    "error": {
        "status": 504,
        "message": "Service didn't reply before timeout"
    }
    }
