### ISSUE TITLE
Popularity missing for tracks

### ISSUE THREAD

**Issue by drsounds** [spotify/web-api#108]
Popularity are missing from tracks result in playlist and albums

**Comment by thelinmichael** [comment]
@drsounds, the Web API object model contains both [simple](https://developer.spotify.com/web-api/object-model/#track-object-simplified) and [full](https://developer.spotify.com/web-api/object-model/#track-object-full) tracks. Playlists contain [Playlist Track objects](https://developer.spotify.com/web-api/object-model/#playlist-object-full), which in turn contain full tracks - so those should have `popularity` set. [Album objects](https://developer.spotify.com/web-api/object-model/#album-object-full) on the other hand contain the simplified track objects, so they do not have `popularity` included. The decision behind is both related to not returning too much unnecessary data, but also to the way the data is structured internally at Spotify.

**Comment by drsounds** [comment]
But that seems to be weird because if you can show popularity in the
desktop client why not in the web api?

Any eta of streaming or play button js api? That would be handy for
projects like Soundbounce if you want the web api to take on the dead apps
api  Now desktop dev are discrimated in favor for mobile
Den 30 sep 2015 12:23 skrev "Michael Thelin" <notifications@github.com>:

**Comment by thelinmichael** [comment]
@drsounds, the popularity is exposed through the Web API, you just need to make an extra request to the Web API to retrieve track popularity. It's important to point out that just because a feature is available in any of the Spotify clients means that it will be exposed in the Web API. There are both technical obstacles as well as business decisions to be made before anything can be implemented and released publicly.

I'd like to keep the discussion in this issue to track popularity, so if you have further questions about the Play Button or web playback, I'd urge you to open a new issue or make a Disqus comment on the Developer site. I can however say that I can't give an ETA on when the Play Button will have a JavaScript API, or if it's going to be released. Basically, don't build anything counting on that functionality being available. I totally understand the use case though.
