### ISSUE TITLE
Error 400 Error Parsing JSON w/ Playlist Create?

### ISSUE THREAD

**Issue by spencerpauly** [spotify/web-api#1112]
#### Endpoint(s):
* `https://api.spotify.com/v1/users/' + {id}+ '/playlists`

#### Scope(s):
Basically all of them

#### Actual behaviour:
400 Server Error (consistently)

`
function createPlaylist(n) {

    var myData = JSON.stringify({name: "test", public: false})

    $.ajax({
        url: 'https://api.spotify.com/v1/users/' + myId + '/playlists',
        method: "POST",
        body: myData,
        headers: {
          'Authorization': 'Bearer ' + access_token,
          'Content-Type': 'application/json'
        },
        success: function(response) {
          console.log(response);
        }
      });
}
`
Why does this return error 400 saying improper JSON? myId is the id that I got from doing a /me ping earlier in the program.

**Comment by bih** [comment]
This is because you're calling the wrong endpoint - you should call `POST /v1/me/playlists` which also doesn't require you to find the current user's ID. For example, this works for me:

```js
function createPlaylist() {
  var myData = JSON.stringify({name: "test", public: false})

  $.ajax({
    url: 'https://api.spotify.com/v1/me/playlists',
    method: "POST",
    body: myData,
    headers: {
      'Authorization': 'Bearer ' + access_token,
      'Content-Type': 'application/json'
    },
    success: function(response) {
      console.log(response);
    }
  });
}
```

As I tested this works, I'll close this issue. If you're continuing to have issues, feel free to comment on this issue and we'll take a look :)
