### ISSUE TITLE
documentation of api limits?

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/web-api#116]
Hi, 

my app has a function to sync all users "saved tracks" to display them as songs, albums, artists. 
https://api.spotify.com/v1/me/tracks

one user reported a problem that he has issues while syncing about 5000 songs.
the limit field of me/tracks request must be <= 50

so i need 100 api calls to fetch these 5000 songs. 

i wonder if there is any documentation regarding api limits. if so, i could update my app to pause after x requests and wait some seconds.

any feedback is welcome

best regards
Alex

**Comment by thelinmichael** [comment]
Hi @digitaldesaster! I recommend adding some artificial slowness to your application so that it makes less intense request bursts. As I'm sure you've noticed a rate limited request gets a `429 Too Many Requests` response. I recommend that you try to use the `Retry-After` header included in that response, since that includes the number of seconds you need to wait until making the next request. We've written some, but admittedly not a lot, documentation on rate limiting, you'll find it in the [User Guide](https://developer.spotify.com/web-api/user-guide/#rate-limiting).

**Comment by digitaldesaster** [comment]
thanks @thelinmichael for the quick feedback. i will take a look in it

**Comment by Roaders** [comment]
I am trying to use the Retry-After header in my app. I have posted a question about it here: 
http://stackoverflow.com/questions/34963169/accessing-headers-in-spotify-api-call-response
My code (angular $http service) is unable to access this header. I suspect it's a cross domain issue and it seems odd to me that Retry-After is not listed in the Access-Control-Allow-Headers header.
Is the API broken or am I doing something wrong?

**Comment by brett84c** [comment]
@Roaders I'm having the same problem.  Did you ever find a solution?  I can't seem to find a "Retry-After" node anywhere.

**Comment by Roaders** [comment]
No, I'm afraid not. I gave up on the application soon after this I am afraid.
