### ISSUE TITLE
"Skip duplicates" parameter when adding to playlists

### ISSUE THREAD

**Issue by rorosaurus** [spotify/web-api#118]
Enhancement request

"Skip duplicates" parameter when adding to playlists, similar to the option presented in the Spotify Client.  Alternatively, responses could indicate whether there was already the same song in the playlist.

Endpoint: https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks

**Comment by thelinmichael** [comment]
@rorosaurus, would an endpoint allowing you to check if a playlist contains certain track URIs work instead? This would allow applications to warn the user that there are duplicates like the Spotify apps do, before adding the tracks.

Request to _Playlist Contains Tracks_: 
`GET https://api.spotify.com/v1/users/{user_id}/playlists/{playlist_id}/tracks/contains?ids={ids}`

Response:
`[ {booleans} ]`

As in your use case, let's say a user wants to add a couple of tracks but you want to check if the user is about to add a duplicate,

1. Make request to Playlist Contains Tracks endpoint to check if any of the tracks are already in the playlist.
2. The response is `[ true, false, false]`
3. Warn the user that the first track they're about to add is already in the playlist.
4. Proceed to call the Add Tracks to Playlist endpoint if the user wants to proceed, otherwise don't.

**Comment by yangshanjin** [comment]
Hello,
I need the libspotify on mips architecture, any help for me would be great, come on, thanks.
please contact me email: sjyangv0@gmail.com

**Comment by rorosaurus** [comment]
That would certainly be sufficient. :)

**Comment by lukaszg84** [comment]
Do you have ETA for this? With larger playlists it takes few unnecessary requests to list all the songs (in chunks of 100) and check for duplicates each time.

**Comment by thelinmichael** [comment]
@lukaszg84, this feature isn't currently being built, so my advise is to not count on it being available if you're building an application right now.

**Comment by dubstrike** [comment]
@thelinmichael This would be great. Have you guys reconsidered adding that parameter? 😀

**Comment by tal** [comment]
@thelinmichael I'd say that the playlist contains endpoint #444 is helpful, it would require 2 requests instead of 1. Having a parameter check would be great as I'm sure the check is cheaper on your end than to spin up 2 different requests.

**Comment by pdaddyo** [comment]
@thelinmichael Any update on this one?  My app https://v2.soundbounce.org/ has an 'add to playlist' feature but I'm concerned about creating duplicates, and enumerating the whole playlist can be risky (i.e. slow) if it's got thousands of tracks.

**Comment by bih** [comment]
Hello @rorosaurus,

As per our [new developer support process](https://github.com/spotify/web-api), any feature requests that have no plans to be considered in the next 6 months will be closed as <kbd>wontfix</kbd>.

In this particular case, this is possible without the need of a potential `skip_duplicates` parameter and there are clear performance benefits as I can see. It's a great suggestion; but given the volume of requests and the lack of large demand for this feature, we have decided not to focus on this for now.

Though I encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Hope this helps! Thanks again and please keep suggesting features 🙂

**Comment by portatlas** [comment]
Would be a nice feature to have.
