### ISSUE TITLE
Getting "Server error" (500) when retrieving user´s playlists via web api

### ISSUE THREAD

**Issue by jholzer** [spotify/web-api#120]
Error can be reproduced with

https://api.spotify.com/v1/users/&lt;username&gt;/playlists?limit=50&offset=0
("&lt;username&gt;" replaced with real user name)

Also tried in API console. Same error.

Issue found 10/15/2015, 19:00 CET

Expected behaviour: Playlists for User

Actual result: "Server error" (500)

**Comment by jholzer** [comment]
...Working again...

**Comment by thelinmichael** [comment]
@jholzer, thanks for reporting it although it was intermittent. We're aware of periodic errors in the playlist endpoints, which happens more often for users with a lot of modifications to their playlists. Hopefully this will decrease in time.

**Comment by tennysontbardwell** [comment]
I've been getting 500 when requesting user playlists. It is intermittent but but occasionally persists for minutes to the better part of an hour. An AWS alarm pesters me every couple of weeks because of it.

Error message:

[DEBUG]	2017-09-13T02:43:22.780Z	4d6*****	https://api.spotify.com:443 "GET /v1/users/spotify/playlists/37i9***** HTTP/1.1" 500 None

**** mark removed characters

**Comment by blackarcanis** [comment]
+1
Same issue there when I'm trying to retrieve a tracklist of a playlist I got occasionally: 
` {"error":{"status":500,"message":"Server error."}}`
Waiting for a couple of seconds and retry the request not working more.
