### ISSUE TITLE
500 error when requesting recommendations

### ISSUE THREAD

**Issue by satyasinha94** [spotify/web-api#1354]
Issue found on October 1st 2019.

When I try to hit the recommendations endpoint without using Spotify's developer console or via curl I get a 500 error. I don't think the access token is an issue because if I try to make a request with an invalid token I get a 401, and I am able to make other requests successfully, such as for a user's top artists. 

#### Endpoint(s):
*   GET https://api.spotify.com/v1/recommendations

#### Scope(s):
* None (application is not using authentication)

#### Code:

```ruby 
# passing in current user instance as argument
def self.top_artist_track_recs(user)
    # refreshes access to the api via the refresh token
    user.refresh 
    #BUG - self.artists returning empty array, using User.find as workaround.
    artist_ids = User.find(user.id).artists.map{|artist| artist.spotify_id}.sample(5).join(",")
    error = nil
    header = {
      Authorization: "Bearer #{user.access_token}"
    }
    begin 
      RestClient.get(
      "https://api.spotify.com/v1/recommendations?market=US&seed_artists=#{artist_ids}", 
       header
      )
    rescue RestClient::InternalServerError => e
      print "ERROR: #{e}"
      error = e.to_s
    end
    if error == nil
      user_response = RestClient.get(
      "https://api.spotify.com/v1/recommendations?market=US&seed_artists=#{artist_ids}", 
       header
       )
      list = JSON.parse(user_response.body)
      recommendations_map(list["tracks"], user)
    else 
      {"error" => error}
    end
  end
```

#### Expected behaviour:
A recommendation response object 

#### Actual behaviour:
500 Server Error (consistently)

**Comment by Fabian-t800** [comment]
Hello!
I've sent the following request via Postman to the endpoint you've mentioned (GET https://api.spotify.com/v1/recommendations)

As parameters I've also added limit, seed_artists and market:

Limit : 100
seed_artists : {{valid_artist_spotify_id}}
market: US

I also use the authorization code in the request header (OAuth2.0).

I do get a 200 response with recommendations.

Please let me know if I've missed any parameter you've been using, so that I may test it again.

Thank you.

**Comment by satyasinha94** [comment]
Closed issue because it seems to have been resolved yesterday evening
