### ISSUE TITLE
Change BPM value of Spotify Song Swift

### ISSUE THREAD

**Issue by shamdass** [spotify/web-api#1357]
I am trying to build an application that plays Spotify songs. I am really confused about how to change BPM(Beats Per Minute,) value of Spotify songs.

**First Step:** Login through Spotify.
**Second Step:** Get Current user all album.
**Third Step:** get album track.
**Last Step:** play track.

I have done All step with Spotify Delegates. but I want to change the BPM value of the track.
I know his is a framework for authenticating with the Spotify API and not a Web API wrapper. But i have little confusion if there is only GET only property then some other application's change Spotify BPM. Is there any special paid service provided by Spotify ya any third party doing this?
Can someone please explain to me how to change the BPM value?

**Comment by kevinguebert** [comment]
The BPM value is only a GET property that one is unable to change using the API. I am _pretty_ sure changing it would also go against the Spotify Terms of Service/Developer ToS. I don't know if/how other apps do it with Spotify but it may be worth reaching out to them as I doubt Spotify will change that.

Also see https://github.com/spotify/ios-sdk/issues/160

**Comment by jscholes** [comment]
This doesn't make much sense - maybe you could clarify?  You may as well be asking how to change the title of a song in Spotify's catalogue, which obviously isn't allowed.  By all means, if you have your own data source which has more accurate BPM values for the songs that you're playing in your app, you can display those to users.  Otherwise this is a content change request and should be communicated via Spotify's standard support channels.

**Comment by shamdass** [comment]
Okay

**Comment by samuelhorwitz** [comment]
That extensions is modifying the playback rate of the media element. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

This is probably some sort of TOS violation regarding Spotify and not official. It's just the reality of the in-browser media playback APIs. Since it's a browser extension that hooks into the Spotify player webpage it's probably able to fly under the radar, but if you use the web streaming SDK with this change hacked in you will almost certainly be violating the TOS (I'm not a lawyer etc). So in other words, it's not possible for all intents and purposes and the way that it is possible is unofficial and hack-y.

**Comment by shamdass** [comment]
Thank you so much @samuelhorwitz   for clarification
