### ISSUE TITLE
Search results return collaborative as false

### ISSUE THREAD

**Issue by bsarkadi** [spotify/web-api#136]
Hi guys,

If you run a search for collaborative playlists (with "collaborative" as keyword) all the returned results have the key "collaborative" set to false even though most of these are indeed collaborative playlists where the value should be true. It seems like a bug to me.

**Comment by JMPerez** [comment]
@bsarkadi When searching for playlists, the returned results normally contain the query as part of the name or the description. Thus, searching for playlists using `collaborative` as the query string doesn't necessarily returns playlists that are collaborative, but rather that their name or description contain this word.

Could you give an example of a collaborative playlist whose `collaborative` field is set to `false`?

**Comment by bsarkadi** [comment]
0:  {
collaborative: false
external_urls: {
spotify: "http://open.spotify.com/user/brit1515/playlist/33rSi2I8GWRbKhbqbITx5S"
}

**Comment by JMPerez** [comment]
@bsarkadi You're right, that playlist is collaborative. Using the web api for fetching that single playlist does report `collaborative` as `true`. You can test it out on [the web api console](https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=33rSi2I8GWRbKhbqbITx5S&user_id=brit1515).

What endpoint are you using to get that result?

**Comment by bsarkadi** [comment]
I've used this:

https://api.spotify.com/v1/search?q=collaborative&type=playlist&limit=50

**Comment by thelinmichael** [comment]
Specifying all playlists as non-collaborative is a way for the API to allow search to include all playlists, without enabling malicious applications to find collaborative playlists by scraping. Some alternatives would be to simply exclude collaborative playlists from the search results, or to set the collaborative property to `null`. I think it's worth re-evaluating or at clarifying in the documentation. Any changes will be posted here @bsarkadi.

**Comment by bsarkadi** [comment]
thanks!

**Comment by bih** [comment]
Hello @bsarkadi,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api). In this case, the rationale for returning `collaborative: false` in all of our search results was already explained by @thelinmichael:
> Specifying all playlists as non-collaborative is a way for the API to allow search to include all playlists, without enabling malicious applications to find collaborative playlists by scraping.

As this discussion hasn't developed since, I will consider this as a <kbd>documentation</kbd> suggestion. We have since made further clarifications to the `collaborative` documentation to specify it will return `false` in the context of search results so other folks have a clearer understanding.

If you'd like to propose a specific suggestion, feel free to create a new issue and reference this one (#136) and we'll be happy to take a look again. Cheers!

Cheers 👍
