### ISSUE TITLE
FFT data for visualizers and playhead information from widget

### ISSUE THREAD

**Issue by GeorgeGardiner** [spotify/web-api#141]
Would it be technically / commercially possible for Spotify widgets to to use HTML5 window.postMessage  to provide play events (start, stop, playhead position) and FFT data for building visualizers?

This has come up a bunch of times for clients including UMG and Virgin EMI who always want Spotify widgets and visualizers on the same page to work with them.

eg. http://bornintheechoes.com/ - just uses the preview MP3 and HTML5 audio as workaround.

Cheers

**Comment by JMPerez** [comment]
Hi @GeorgeGardiner. This is something we have been thinking for some time and would definitely like to support, but can't any specific commitment at the moment. I will bring this up with the team working on the Spotify Play Button.

**Comment by JMPerez** [comment]
@GeorgeGardiner, We would like to keep this repo as the place to talk about the Web API. Since this issue is related with the Spotify Play Button and not the Web API, we will backlog it and close it.

Any changes made in the Spotify Play Button will be announced through [its page on the Spotify's Developer site](https://developer.spotify.com/technologies/widgets/spotify-play-button/) and the [@SpotifyPlatform Twitter account](https://twitter.com/SpotifyPlatform).
