### ISSUE TITLE
Get more data with track request

### ISSUE THREAD

**Issue by ASCrookes** [spotify/web-api#144]
Are there any plans to make a request to get a spotify track and also request that the artist object contains their avatar? Sample request https://api.spotify.com/v1/tracks/60EtWSoDRJSFmg99MKZi0x
It would be great if the artist's avatar url or more details were in the artist object. For now to get all the necessary information I have to make two requests that have to be run in series since the 2nd call depends on the result of the first.

**Comment by thelinmichael** [comment]
Hey @ASCrookes! 

Some background if someone else arrives here:
The Get Track endpoint returns so called [Full Track objects](https://developer.spotify.com/web-api/object-model/#track-object-full). These objects in turn contain a list of [Simple Artist objects](https://developer.spotify.com/web-api/object-model/#artist-object-simplified), and not Full Artist objects. The Simple Artist objects contain less data than the Full. One property that isn't included in the Simple Artist object is the artist's image.

No, there aren't any plans to include the artist's image data into the full track object. There are a few reasons for this - e.g. reducing traffic by not sending data unless it's needed by a lot of use cases. Another reason is to reduce the amount of data for a dependency (artist in the case of track, and owner in the case of a playlist) since it makes caching less useful. I'll however add an enhancement sticker on this issue since more people might want to include artist images in the Full Track object.

**Comment by asmitter** [comment]
(Cleaning up old tickets)
We've no plans to extend the track object with the artist image.
@thelinmichael did a good job of explaining the tradeoff, and you can always fetch the artist info (including image) from a full track object by doing a subsequent call to the `href` property value found in the artist object.
