### ISSUE TITLE
API key block / expires to fast

### ISSUE THREAD

**Issue by h-pauwelyn** [spotify/web-api#149]
I've request a API key to get the users playlist. All my code works, but the only problem is that the key block or expires to fast. I use this code:

        $.ajax({
            url: "https://api.spotify.com/v1/users/" + $("#gebruiker").val() + "/playlists",
            headers: {
                Authorization: "Bearer " + my key
            },
            Host: "api.spotify.com",
            Accept: "application/json",
            type: "GET",
            success: function (data){
                //code
            },
            error: function (data) {
                //code
            }
        });

When blocks or expires the API key from Spotify and what can you do about this?

**Comment by h-pauwelyn** [comment]
On Stack Overflow I've ask it also an an answer that I had is this

>Access tokens are deliberately set to expire after a short time, after which new tokens may be granted by supplying the refresh token originally obtained during the authorization code exchange. As explained in the https://developer.spotify.com/web-api/authorization-guide/

**Comment by thelinmichael** [comment]
That's correct @h-pauwelyn, thanks for supplying the answer here so that others can find it. Count on the access token working for 60 minutes - the exact expiry time is returned in the response along with the access token. I'll close this ticket, please re-open it if you're experiencing something that's not aligned with what's in the documentation.
