### ISSUE TITLE
Delete Request With Body Alternative

### ISSUE THREAD

**Issue by JustinTipton** [spotify/web-api#155]
As Google App Engine doesn't support delete requests with body payloads, I'm requesting delete requests in the API to have post versions as an alternative.

**Comment by StagasaurusRex** [comment]
+1 Workflow on iOS doesn't support delete requests with a body either. An alternative would be nice.

**Comment by wdehoog** [comment]
+1 QML applications on SailfishOS also cannot have a body for DELETE requests. An alternative is needed.

**Comment by bih** [comment]
Hello @JustinTipton,
Hello [NAME],

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api), and given this particular suggestion has received no engagement for a while, I will close this ticket as <kbd>inactive</kbd>.

Of course, if you'd like to bring up this suggestion again, feel free to create a new issue! Otherwise, if we have anything related to this to share, we will post it here for your convenience!

Cheers 👍
