### ISSUE TITLE
Time interval objects do no include first item.

### ISSUE THREAD

**Issue by GabeDahl** [spotify/web-api#1551]
Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/audio-analysis/{id}`

#### Scope(s):
* None 

#### Steps to reproduce:
1. Open the API Console
2. Call the audio analysis for a track 

#### Expected behaviour:
An object which includes an array of 'segment' objects. Each segment object should have a key of 'start.'
The 'start' key for the first item should have a value of '0'.
Repeat with 'sections', 'bars', 'tatums', etc.

#### Actual behaviour:
An object which includes an array of 'segment' objects. The first object has no 'start' key.

**Comment by GabeDahl** [comment]
My current workout is to manually set the first object's 'start' to 0

**Comment by endanke** [comment]
Not sure if it's related to this issue, but I noticed that since yesterday several properties are missing from the 'audio-analysis' response. For example, I don't see the confidence property in the last object of the 'bars' array,  the 'key_confidence' and 'tempo_confidence' also missing from some section objects.
I also don't see the 'start' field in some cases, like you mentioned. Two days ago my client was working without any parsing issues, so I assume it might be a server-side problem?

**Comment by GabeDahl** [comment]
I just tried a few tests and received the same result in the web console provided at https://developer.spotify.com/console/
Like you say - it must be server-side. 
Unless they decided to updated the API without updating the docs

**Comment by joshubrown** [comment]
Thanks for reporting this, folks. We've made some updates and think the issue should be resolved now. If you notice this or another API problem happening again then please let us know over in the [Spotify for Developers forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
