### ISSUE TITLE
Authorisation flow for Smart TVs (input/web limited devices)

### ISSUE THREAD

**Issue by jsancho** [spotify/web-api#168]
Hi, I'm building a Spotify client for Samsung Smart TVs (Tizen platform).
The app is essentially a bundle of JavaScript and html that is downloaded onto the TV itself.
I was wondering if there is a "device flow" similar to that of Facebook (see link below) or Plex, which allows to perform the login onto a different device by means of a pin/code.
https://developers.facebook.com/docs/facebook-login/for-devices

The problem with the authorisation methods described in the Spotify documentation is that the app requires having an available url to which the user can be redirected to, as per the typical OAuth flow. 
However, this app is running embedded on the TV, as if it was in a native environment. It can't quite open up a browser session, do the login and redirect back to an arbitrary web domain, as there is no web session per se.

A code-based authorisation system, like the Facebook one that I've linked, would make this possible.
The other benefit being, that typing account names and passwords can be rather awkward with a standard TV remote. Using a code on an external device would make this process much more user-friendly.

Or alternatively, are there any other methods that you might suggest to authorise a user in this scenario?

Thanks very much,

Jaume

**Comment by hughrawlinson** [comment]
Hey Jaume, thanks for getting in touch. We don't currently have this authorisation flow available, but I will pass it on as a feature request to the relevant team. Thanks!

**Comment by bih** [comment]
Hello @jsancho,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api), and given this particular feature suggestion has received no engagement for a while, I will close this ticket as <kbd>inactive</kbd> for a clearer support process.

Of course, if you'd like to bring up this issue again, feel free to create a new issue! Otherwise, we will post updates here if any releases related to this exist.

Cheers! 👍
