### ISSUE TITLE
Invalid redirect URI

### ISSUE THREAD

**Issue by JosephSmith127** [spotify/web-api#171]
So I have the exact same setup on local as I do on production... both the URIs are correct within the spotify app... although on production it is https:// and not http:// 

Local -> works
Production -> doesn't

would it being a https:// redirect effect it? I have added both the http:// and the https:// to the accepted redirect routes. Still nothing?

**Comment by Pau1fitz** [comment]
@JosephSmith127 did you manage to deploy on production in the end?

For me, authentication is working locally, however when I deploy to a production server the authentication breaks at the point after the user accepts that i can access their data. Instead of getting an access_token and refresh_token in the redirect_uri, I instead get `?code`. Have you seen this before? e.g. `http://redirect_uri.net/?code=xxxKok&state=xxxx`
