### ISSUE TITLE
Top Tracks On Artist Search

### ISSUE THREAD

**Issue by treygeorge** [spotify/web-api#18]
When using the https://api.spotify.com/v1/search endpoint with type=artist, it would be nice to have the option to return back that artist's top tracks.  As it stands I have to use the search endpoint to get the artist's ID and then make another call to get top tracks once I have the artist's ID.

**Comment by thelinmichael** [comment]
Hi @treygeorge! 

The need to retrieve every artists' top tracks as part of a search is, as I view it, not a common enough use case to warrant its implementation. It would also mean that other endpoints may need similar options for consistency, and it would potentially also have impact on the search endpoint's caching rules. 

Since the API is quite forgiving regarding rate limits, especially for authenticated requests, I believe the work that's needed to enable this isn't important enough to let it be prioritised over other features. Caching top tracks responses on your side if possible might help.
