### ISSUE TITLE
ISRCs not returned?

### ISSUE THREAD

**Issue by andcam** [spotify/web-api#182]
Hello - looks like the ISRCs are no longer returned in albums or tracks in the Web API?

This means we can no-longer match Spotify data with our internal recording data (as a label).

Any reason for this? Or am I missing something?

TIA.

**Comment by thelinmichael** [comment]
@andcam, are you still seeing a lack of ISRCs from the Web API? Also, are you using ISRCs for albums as well? I recommend looking at UPC for that.

**Comment by andcam** [comment]
@thelinmichael we use id to identify albums, UPC to match it and loop through the tracks to relate them by ISRC to our internal database.

ISRCs are not returned in albums:

https://api.spotify.com/v1/albums/7JmL7dg7w0hJTyIFXbZpEU

We could loop through query every track individually but that's a helluva lot of effort (and data duplication) just to get the missing ISRC field (that was return in the old API)

**Comment by thelinmichael** [comment]
Thanks for clarifying @andcam. What's needed is to include `external_ids` in the [simplified Track object](https://developer.spotify.com/web-api/object-model/#track-object-simplified). (Since the returned object from the [Get Album endpoint](https://developer.spotify.com/web-api/get-album/) is a [full Album object](https://developer.spotify.com/web-api/object-model/#album-object-full), which in turn contains simple Track objects.) `external_ids` is currently only available in the full Track object.

The reasoning behind hiding some of the track metadata when looking up albums is that it's not likely to be needed, and would decrease the size of the response. There are obvious drawbacks to this as well,  your issue being a good example.

Labeling this issue as an enhancement request since we'd need to consider modifying the simplified Track object.

**Comment by ahallora** [comment]
If you could also provide the UPC (if available) in the external_ids object that would be great! :+1:

**Comment by reinierbutot** [comment]
We also use this data internally (at a label) and match tracks using a combination of the isrc and upc. This means listing the UPC code for individual tracks would solve a lot of problems.

**Comment by chasenyc** [comment]
Is this enhancement still being considered?

**Comment by bih** [comment]
Hello @andcam,

As per [our updated developer support process](https://github.com/spotify/web-api), we will close issues that have been inactive after an extended period of time. Often it is because those issues have been resolved, but the GitHub issue itself has not.

In this case, I can see the `upc` is being exposed and the `isrc` is available for tracks besides for the simplified track object. This means it is possible to do this, but for performance reasons, having it in the simplified track object would be better.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritise features going forward. You should be able to comment on this issue even after it is closed. We will also post updates here relating to this suggestion as and when they happen.

Hope this clears things up. Cheers 👍
