### ISSUE TITLE
a in h1 overrides color

### ISSUE THREAD

**Issue by jayenashar** [spotify/web-api#19]
https://developer.spotify.com/technologies/widgets/spotify-follow-button/

for dark backgrounds, the color on the `h1` tries to be a light color, but the `a` overrides it, resulting in a hidden artist name

**Comment by thelinmichael** [comment]
Thanks @jayenashar, it's a known issue but we of course appreciate that you're letting us know about it. I'm going to close this issue since we're only keeping Web API related bugs and feature requests in this repository. Disqus pages is currently the best way to give feedback regarding the Follow button. Thanks again!
