### ISSUE TITLE
500 Server error when refreshing token without Content-Type header

### ISSUE THREAD

**Issue by Swoosh1** [spotify/web-api#190]
I get 400 errors with the error: "{"error":"invalid_client","error_description":"Invalid client"}" with the following requests:

POST https://accounts.spotify.com/api/token HTTP/1.1
Authorization: Basic ZW.....U=
Content-Type: application/x-www-form-urlencoded
Host: accounts.spotify.com
Content-Length: 170
Expect: 100-continue
Connection: Keep-Alive

grant_type=refresh_token&refresh_token=AQA....Wmkp5qc

I get 500 errors with the error: {"error":"server_error"} with the following request (the only difference is I do not set Content-Type):

POST https://accounts.spotify.com/api/token HTTP/1.1
Authorization: Basic ZW.....U=
Host: accounts.spotify.com
Content-Length: 170
Expect: 100-continue
Connection: Keep-Alive

grant_type=refresh_token&refresh_token=AQA....Wmkp5qc

I have created a new application and the issue persists. Any help would be much appreciated as I have run out of ideas!

Thanks

**Comment by thelinmichael** [comment]
Thanks @Swoosh1!

Please double check that you're creating the Authorization header value correctly - I'm assuming that you've successfully exchanged the authorization code for an access token, as documented in Step 4 in the [Authorization Guide](https://developer.spotify.com/web-api/authorization-guide/#authorization_code_flow). 

I've found that a common reason for this problem is that the base 64 encoded string has been created with a new line, e.g. `echo {client_id}:{client_secret} | base64 -` instead of `echo -n {client_id}:{client_secret} | base64 -`.

If you're still having this issue, please create a new issue ticket for it so that we can focus on the 500 response in this one. It's easier to get an overview of the status of existing bugs that way.

Regarding the 500 response, it's easy to reproduce it and we'll have to have a look closer at it. Good catch!

Example:
```bash
$ curl -ik -X POST "https://accounts.spotify.com/api/token"

HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Tue, 29 Mar 2016 05:20:51 GMT
Content-Type: application/json
Content-Length: 24
Connection: keep-alive
Keep-Alive: timeout=10

{"error":"server_error"}
```

**Comment by oswaldoferreira** [comment]
+1

Getting `415` when sending `Content-Type: application/json` and `500` when sending no content-type (also on the 5th step),  here's a request sample:

Body:
```
{
    "grant_type": "authorization_code",
    "redirect_uri": "callback-url",
    "code": "code from previous step"
}
```

Headers:

```
Authorization: Basic <base64 client_id:client_secret>
Content-Type: application/json
```

**Comment by JBarna** [comment]
I am also having this issue. Unless I include the header "Content-Type": "application/x-www-form-urlencoded" the server responds with a `{ error: 'server_error',
  error_description: 'Unexpected status: 400' }`

**Comment by tr0gd0r** [comment]
thanks @JBarna, was implementing spotify_token_swap.rb in lua and was getting that error until I added "Content-Type": "application/x-www-form-urlencoded"

**Comment by Swoosh1** [comment]
Sorry about the delay in this but the issue was actually how I was writing the body content to the request. I was using streamcontent, switched it to stringcontent and it resolved my issue.

**Comment by ikhanal** [comment]
@Swoosh1  What do you mean by stringcontent insteda streamcontent? Where did you change it? I got similar issue bt I could not figure out yet?
