### ISSUE TITLE
503 server unavailable returned when "/" appears in song title

### ISSUE THREAD

**Issue by zerocarbthirty** [spotify/web-api#195]
Hi,

Using this code https://github.com/dlrudie/Snip/blob/master/Snip/Players/Spotify.cs anytime we hit https://api.spotify.com/v1/search?q={0}&type=track with a "/" in the song title we get a 503 server unavailable error back. Any idea when this will be fixed?

thanks,
ZCT

**Comment by hughrawlinson** [comment]
Hey @zerocarbthirty, have you tried using '%2F' instead of '/'? Usually, strings in query parameters should be urlencoded so that characters that have syntactic meaning in the url get escaped.

**Comment by zerocarbthirty** [comment]
hi @hughrawlinson 

Starting on line 290 on the file I referenced:

var downloadedJson = jsonWebClient.DownloadString(
                        string.Format(
                            CultureInfo.InvariantCulture,
                            "https://api.spotify.com/v1/search?q={0}&type=track",
                            HttpUtility.UrlEncode(spotifyTitle)));

it looks like it should already be urlencoded

**Comment by jsimonsson** [comment]
@zerocarbthirty @hughrawlinson It is correct that it needs to be url encoded, but we also have a bug that is beeing fixed right now where slashes in the search query actually gives 404 (not seen 503's tho), a regression we did not catch. I'll notify you when we have deployed a fix.

**Comment by thelinmichael** [comment]
Unable to recreate this unfortunately. For example, searching for "20 20" will return tracks named "20/20", see [API Console link to request](https://developer.spotify.com/web-api/console/get-search-item/?q=20+20&type=track). If this request returned a 503, it could've been a temporary error in the Web API. Could you please double-check @zerocarbthirty?

Like @jsimonsson mentions, we've aware of an issue in the Search endpoint where queries including a slash `/` returns a response with status code `404 Not Found`. This bug is tracked in #187.

**Comment by thelinmichael** [comment]
Closing this one - please open it again if you've got more information @zerocarbthirty!
