### ISSUE TITLE
iOS rejection because of ipv6

### ISSUE THREAD

**Issue by Jaiyo** [spotify/web-api#270]
It seems the API servers do not run ipv6? Because of that Apple is rejecting apps using the web api.

**Comment by thelinmichael** [comment]
Thanks for the report @Jaiyo. Let us do some investigation on our side and get back to you.

**Comment by hughrawlinson** [comment]
Hi @Jaiyo, sorry it's taken so long to get back to you. We currently don't support IPv6 at all due to the fact that some of our infrastructure is running on Google Cloud Platform which [doesn't support IPv6 at all](https://cloud.google.com/compute/docs/networking). One possible solution to this is to query the API via your own server. Sorry we can't resolve this right now.
