### ISSUE TITLE
No results returned in HTTPS::Get search using tag:new at specific offset

### ISSUE THREAD

**Issue by dotfield** [spotify/web-api#273]
I have a script that runs every Sunday to find new releases on Spotify. This does a search based on tag:new and then I do further searches to get metadata from the results (artists, title of first track, uri of first track and number of tracks)

Yesterday, I was getting "empty" results on calls like this:

https://api.spotify.com/v1/search?query=tag%3Anew&offset=28355&limit=50&type=album&market=GB

This call failed regularly yesterday. Changing the offset to 28356 seemed to fix it instantly (but I had to restart the program to do that, and then of course I lose the result at offset 28355).

Incidentally, I think it would be preferable to be able to do a big search with a single request followed by a "more" request rather than repeating the search with different offsets, although that would require you to cache the initial search results and provide an id for it that I would quote in subsequent calls for more data, so I don't know how well that fits into a connectionless search API. (It would surely be more efficient though)

**Comment by hughrawlinson** [comment]
Thanks for getting in touch @dotfield! I'll pass this bug info and your feedback on to the team that manages search. Did you happen to save the timestamp and/or status code of any of the failed requests? Interesting thoughts on a `more` parameter - we'll keep that in mind.

It seems like the request is working at the moment, so I'll close this issue and let the team investigate if there was something wrong with any of our services yesterday. Do feel free to reopen if this issue comes up again though. Thanks! 😄
