### ISSUE TITLE
502 - Failed To Get Following Artists

### ISSUE THREAD

**Issue by michaelfoster9** [spotify/web-api#275]
My application is trying to get a list of all of the artists that the user follows using the following api
https://api.spotify.com/v1/me/following

I am using a page size of 50.  The user is following about 2000 artists but i am getting a failure on the 4th or 5th page.  I get the failure every single time for a specific user.  I have had 5 or 6 other users report the same problem.

The error that I am seeing is below.  I have no way of knowing exactly which artist is causing the problem but I know that once the error occurs for that user, i can't retrieve the rest of the artists. This is a problem because then my app only works on the artists that were retrieved on the first few pages before the error occurred.

"{\n  \"error\": {\n    \"status\": 502,\n    \"message\": \"Failed to get followed artists\"\n  }\n}"

Are you aware of a workaround that I can use to prevent this error or anything i can offer for you to reproduce this?  The user ID that causes the problem is : 1241745114

**Comment by hughrawlinson** [comment]
Hey @michaelfoster9 - I'll forward this report on to the team that manages that service, and let them get back to you. Thanks for reporting this bug! 🐛 ✨

**Comment by michaelfoster9** [comment]
@hughrawlinson : I'm just checking in to see if this issue has been reproduced and if there will be a forthcoming fix for it.  Without it, i need to find an alternative for getting a list of artists the user follows because with this defect, the feature is neutered for some percentage of my user base.

thanks,
michael

**Comment by bluetidepro** [comment]
Any update on this feature/bug being fixed?

**Comment by hughrawlinson** [comment]
Hey @michaelfoster9 - we've discovered the issue. Your user was following an invalid Artist, due to an old issue with the Spotify client. This data is being cleaned up to prevent this issue from happening again, and a fix will has been rolled out that prevents users from following invalid artists. Your users follow list should be corrected now. If you encounter users with this issue in the future, please ask them to contact Spotify support, who should be able to help the individual user. Please feel free to get in touch with us if you encounter any more issues.
