### ISSUE TITLE
Endpoint for updating an artist's events

### ISSUE THREAD

**Issue by fightbulc** [spotify/web-api#283]
At the moment they only way to integrate events is to go via Songkick. I have a growing number of artists which would like to push their events via the Pushcast service.

Is there any plan for this feature?

**Comment by thelinmichael** [comment]
Hi @fightbulc! Is this feature request related to Spotify as a whole, or the web API? As you've probably noticed the web API doesn't expose any functionality related to events, and there are no immediate plans to do so. If you're requesting that Spotify expands it's ingestion of events data to include new providers, the [Spotify Community](https://community.spotify.com) is better suited to host that feature request since the scope of this repository only includes the web API.
