### ISSUE TITLE
Edit the Current User's Profile Details

### ISSUE THREAD

**Issue by mktoni** [spotify/web-api#30]
Please add some PUT actions in **User Profile Endpoints**. I'd like to be able to modify my display name and my profile image but, unfortunately, there is no way of doing that directly in my spotify account.

**Comment by mmontag** [comment]
+1

**Comment by bih** [comment]
Hello @mktoni,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api), and given we have no plans to prioritise this suggestion in the next 6 months, we will close this ticket as per our process.

Of course, if you have any additional cases and/or ideas to share, feel free to comment on this issue. Otherwise, we will post here if there are any updates relating to being able to programmatically edit a user's profile!

Cheers 👍

**Comment by mktoni** [comment]
It is disappointing that Spotify didn't have decoupled the user profiles from Facebook account yet. There is no way of editing a user profile neither programatically nor through any of the apps, unless you link the Spotify account with FB.

**Comment by bih** [comment]
@mktoni It is possible to manually decouple your user profile, if you contact the lovely folks over at [Spotify Customer Support](https://support.spotify.com). There isn't a way to do this programmatically right now, though it is something I can see us having in the near future, and when there is progress to share, we will re-open this issue and share updates.
