### ISSUE TITLE
Allow non-owners to add to collaborative playlists

### ISSUE THREAD

**Issue by jiaweizhang** [spotify/web-api#334]
The following [page](https://developer.spotify.com/web-api/working-with-playlists/) states that when using the Web API, only the owner of a collaborative playlist can make changes to that playlist.

I believe that means that the owner's friends can't add/reorder/delete songs from that playlist. I am planning on building a collaborative music tool in 2 weeks at HackNC and would like for any "friend" of the playlist owner to modify playlists (functionality that exists with the Desktop Spotify App). 

Alternatively, would it be against Spotify's ToS to store the owner's auth_token (and fetch refresh tokens at intervals) and use that auth_token to spoof the requests as coming from the owner? 

Thanks!

**Comment by thelinmichael** [comment]
Hey @jiaweizhang! 

This enhancement request is covered in #100. 

> Alternatively, would it be against Spotify's ToS to store the owner's auth_token (and fetch refresh tokens at intervals) and use that auth_token to spoof the requests as coming from the owner?

Our advise is to read the ToS carefully and do your best to adhere to it - we can't give legal advise. From a technical standpoint it's definitely possible to do though. One side-effect that you may not want is that you can't tell who wanted to have a track added, since all tracks will be added by the owner.

Have fun at HackNC!
