### ISSUE TITLE
Sort tracks by release date and time

### ISSUE THREAD

**Issue by wooptoo** [spotify/web-api#359]
I've found that there is no obvious way to sort an artist's songs by the release date and time. This would be extremely useful in order to get the latest released tracks of an artist.  
It seems like the API does not expose a date/time on the tracks themselves, making it very hard to figure out the latest releases on my side.

**Comment by hughrawlinson** [comment]
Hey @wooptoo, thanks for the feedback!

I'll pass on the feedback of having release dates available on the track object. The reason that's not currently the case is that all tracks are part of a release, and releases are the object with release dates. The use case for getting the latest released tracks is catered for in the artists/[id]/albums endpoint - the albums should be sorted in chronological order (most recent to oldest) just like in the Spotify client. From there you can pick the latest album and grab the tracks from it. That endpoint handles types: single, album, appears_on, and compilation, so it'll work for individually released tracks too. You could grab the latest single for example by calling

```
curl -X GET "https://api.spotify.com/v1/artists/1dfeR4HaWDbWqFHLkxsg1d/albums?album_type=single&market=GB&limit=1" -H "Accept: application/json"
```

In order to get the latest release (of any release type) you can just leave out the `album_type=single` query parameter.

I'll close this issue because I've addressed the primary use-case you described, but please feel free to reopen it if you have another use case that I haven't addressed.

**Comment by wooptoo** [comment]
Thanks @hughrawlinson that was very helpful

**Comment by ianrandmckenzie** [comment]
Hi there, 

I have a use case where an album's release date (or Spotify release date, more preferably) is necessary. I am creating a chronological feed of social content, including artists' album releases on Spotify. A date would be really handy for showing the album in my users' feeds at the time it was released on Spotify.

In the meantime, I'll have to find a more arbitrary means of displaying Spotify content, which is less than ideal.

Thank you,

Ian

**Comment by scottiejibbs** [comment]
@ianrandmckenzie - maybe I misunderstand your exact use case, but I believe I'm doing what you describe.  the "albums/" endpoint *does* provide a release_date.  the only hurdle i encountered, was that my feed was individual *tracks* pulled from user playlists (spanning a variety of albums), and individual tracks currently don't directly provide release date information.  the track data *does* include the album id so it just required me hitting the "albums/" end point also for each track to retrieve the release_date information, populating my internal track objects with that info, then i'm free to display my feed of tracks sorted by release date.  hope that helps.

-Scott

**Comment by ianrandmckenzie** [comment]
That does help, thanks @scottiejibbs 

It turns out I wasn't seeing a release date because I was using this endpoint:
`https://api.spotify.com/v1/artists/{id}/albums`

When I get an album through the 'artists' endpoint, the release date isn't included.
