### ISSUE TITLE
public shared playlists

### ISSUE THREAD

**Issue by joaomesq** [spotify/web-api#37]
Hi,

I would like to have the option of getting playlists shared by a group of users, in order to discover which users have the same tastes in music, for a data viz exercise class.

Btw, is weird that I can get a user private playlist data in the web console and not the public shared playlists. From my point of view, if privacy is a concern it should be the other way around.

Thank you.

**Comment by fsahin** [comment]
Thanks for your suggestion. In this case, your collaborative playlists are a bigger problem than your public playlists, because they are editable by anyone whoever has the uri to it. We are considering a read only access to collaborative playlists as a first step but I can't give you a date on when it will happen. 

Since there is already another ticket about this matter (#6), I will close this one and ask you to follow the progress on the other one. Thank you.
