### ISSUE TITLE
After deploying from local machine to server getting error message - No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by Pau1fitz** [spotify/web-api#373]
From the front end and through jQuery I am making `GET` requests to a `node/express` app. This app then speaks to the Spotify API to authenticate a user. I am getting the following error message when I try and make a call to the `user-playlist` endpoint that I have created. This endpoint retrieves all the playlists that the current user has. 

> :8000/#access_token=AccessTokenProvidedBySpotify
> XMLHttpRequest cannot load
> http://XXX.XX.XXX.XXX/user-playlist. Response to preflight
> request doesn't pass access control check: No
> 'Access-Control-Allow-Origin' header is present on the requested
> resource. Origin 'http://XXX.XX.XXX.XXX:8000' is therefore not allowed
> access.

I have tried adding the following code to my `app.js` express app, but it didn't work. I tried everything else i could find online too, but cannot get it working.

    var app = express();
    app.use(function(req, res, next) {
      res.header("Access-Control-Allow-Origin", "*");
      res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
      next();
    });

    app.get('/create-playlist', function(req, res){
        var options = {
            url: 'https://api.spotify.com/v1/me',
            headers: {
                'Authorization': 'Bearer ' + access_token
            },
            json: true
        };
    
        requestPromise(options).then(function(body) {
            userEmail = body.email;
            userId = body.id;
            var optionsTwo = {
                url: 'https://api.spotify.com/v1/users/' + userId + '/playlists',
                headers: {
                    'Authorization': 'Bearer ' + access_token
                },
                json: true
            };
            return rp(optionsTwo).then(function (body) {
                playlists = body.items;
                res.json(playlists);
            });
        }).catch(function (err) {
            console.log(err)
        })
    });

**EDIT**

I have also implemented an answer that I found on SO, that I have provided below, but this doesn't work either. If I `console.log(req.method)` it is always `GET`, it never shows `OPTIONS`.

    var app = express();
    app.use(function(req, res, next) {
      res.header("Access-Control-Allow-Origin", "*");
      res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
      if (req.method === 'OPTIONS') {
        return res.send(200);
      } else {
        return next();
      }
    });

My front end code looks like this:

    $.ajax({
    	type: 'POST',
    	url: 'http://xxx.xx.xxx.xxx/user-playlist',
    	contentType: 'application/json',
    	success: function(data) {
    		console.log(data)
    	}
    });

**Comment by hughrawlinson** [comment]
Hey @Pau1fitz - this isn't an issue with the Web API, but I thought I'd help out anyway.

It looks like you don't have any routes registered to respond to `OPTIONS` requests. Even though you have the middleware adding the CORS headers to each response, your express app isn't actually listening for `OPTIONS` requests. When you log `req.method` inside your `app.get` handler, it only logs `GET` because express doesn't know to use that handler for `OPTIONS` requests (so it's probably serving `404` responses to them).

You're nearly there with your current middleware that adds the CORS headers to all responses, you just have to make sure that `OPTIONS` requests get matched by the express router and responded to properly. [Here's a gist](https://gist.github.com/cuppster/2344435) explaining how you would do that, but the TL;DR is: Add the following code to the bottom of your CORS header middleware callback:

```
// intercept OPTIONS method
if ('OPTIONS' == req.method) {
  res.send(200);
}
else {
  next();
}
```

Hope that helps!

**Comment by Pau1fitz** [comment]
@hughrawlinson  thanks for this!
