### ISSUE TITLE
Ability to view song/album credits

### ISSUE THREAD

**Issue by danielgbarreto** [spotify/web-api#376]
Song/album credits information, such as musicians, producers and engineers who worked on each song are not yet supported by Spotify.

I'd like to suggest support for this into your apps.

**Comment by jotasprout** [comment]
Wouldn't this be the more true and accurate way to find "related artists"? I'd LOVE this. At present I'm trying to figure out a way to combine the Spotify API and scrape Wikipedia to come up with something like this.

**Comment by danielgbarreto** [comment]
There is a site called All Music that shares this kind of data. They say it comes from their data provider, Rovi (now called TiVo). Maybe it's a better source than Wikipedia, mainly when it comes to projects there are not super popular.

**Comment by thelinmichael** [comment]
Hi @danielgbarreto! Thanks for your feature request. Since this data isn't exposed anywhere in Spotify's applications, it'd be more appropriate to share your idea with the [Spotify Community](http://community.spotify.com/). This Github repository is only for Spotify's web API, and the scope of this request is a lot wider than that.)
