### ISSUE TITLE
Time signature

### ISSUE THREAD

**Issue by mortenhjort** [spotify/web-api#379]
I think I've found a bug on this track ID: 42TP2X3293Cou18ekXt2xq. It just displays 1, which doesn't make any sense. And in that regard: is there any place where the outputs from Spotify can be found? Like the track "Take Five" is displayed with a 5. But is that then 5/4 or 5/8?

**Comment by thelinmichael** [comment]
Hey @mortenhjort! Having some trouble reproducing this issue. Where is the track represented by a `1`?

**Comment by mortenhjort** [comment]
hi @thelinmichael the track ID is above (42TP2X3293Cou18ekXt2xq). Try to put that into the console and you'll see the time signature as "1". Do you have an answer in regard to the more overall question?

**Comment by thelinmichael** [comment]
@mortenhjort, what do you mean by time signature?

**Comment by mortenhjort** [comment]
@thelinmichael Time signature is part of the Audio Features endpoint: https://developer.spotify.com/web-api/get-audio-features/

**Comment by cormacparle** [comment]
@mortenhjort the time_signature documentation says "The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure)" - how many beats, and not what those beats are, so it's not going to distinguish between 5/4 and 5/8

On the spotify web player the album is https://play.spotify.com/album/196bKLiC2RBltX8dm5uWnM/3pggQzQ4zgv3kZnb8p2WEa and the track is number 3 ... time signature is 7/4 so the /audio-features/{id} request should return time_signature=7 instead of 1

**Comment by hughrawlinson** [comment]
Hey @mortenhjort - thanks for reporting this issue. Audio Features are extracted using machine learning models, which work quite well but occasionally get the values wrong, particularly for unusual data. In this case the song is in 7/4, which is fairly unusual in its timbral/genre context. I've reported this song to the team in charge of the models so that they can flag it and hopefully use it to improve the models, but it's always possible that some of the audio features data will be a little off. Thanks for reporting!
