### ISSUE TITLE
get starred Songs (hidden api call) ?

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/web-api#39]
Hi, 

EDIT
just saw that the "star" function was removed many months ago. so i think this is obsolete until there is a new official star function.

#################################
i wonder why this function is not documented.

https://api.spotify.com/v1/users/<userID>/starred

it works but it is not documented. 
if would be great to have this as official feature, also in the Android SDK.
furthermore options to star/unstar a song would be great.

**Comment by thelinmichael** [comment]
Hey @digitaldesaster. The reason for it not being documented is because it's not officially supported and may be removed at any time. The concept of Starred tracks has been replaced with Your Music, as mentioned on the [Spotify support site](https://support.spotify.com/us/learn-more/faq/#!/article/what-happened-to-starred-tracks).
