### ISSUE TITLE
"Get An Album" API call always returns empty Genres list

### ISSUE THREAD

**Issue by pravisas3** [spotify/web-api#390]
Issue found on Jan 6, 2017.

#### Endpoint(s):
* `GET https://api.spotify.com/v1/albums/{id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the Get An Album API with an Album ID
2a. Album IDs tried were 3H0HdocoAAEEfiDfcRZauz, 70lQYZtypdCALtFVlQAcvx and 1TKCBDHIWLiqjWTxomqniD

#### Expected behaviour:
The Genres list in the returned JSON object must contain Genre information. For the three albums above, I'd expect the Genres to be Blues, Rock and Metal.

#### Actual behaviour:
Genres list is always empty.

**Comment by hughrawlinson** [comment]
At the moment, genres are attached to tracks, not to albums. Albums can contain a wide variety of genres, so attempting to label them can give inaccurate data. We haven't removed the field from the model because that would be a breaking change, and there's a possibility that we'll reintroduce album genres later.

**Comment by michelle-chiang** [comment]
@hughrawlinson could you specify where to find the track genre information? None of the API track endpoints (https://developer.spotify.com/web-api/track-endpoints/) list it as a valid field.
