### ISSUE TITLE
The FILL SAMPLE DATA button in the API Console for the /v1/me endpoint is unhelpful

### ISSUE THREAD

**Issue by anamud** [spotify/web-api#404]
The button simply does nothing. This can be surprising to new-comers who saw it work for the other tests. For example, tests with the /v1/users/{users_id} endpoint. The button also drives the idea that sample OAuth tokens, hopefully for fictitious users, can be filled in. I anticipate serious problems with supporting sample OAuth tokens for fictitious users. The only suggestion I have is to remove the unhelpful button.

**Comment by hughrawlinson** [comment]
Thanks for the report @anamud!

**Comment by hughrawlinson** [comment]
Hey @anamud - we've decided to keep the Fill Sample Data button, but we've made some changes. It no longer appears [on pages that do not have any sample data fields](https://developer.spotify.com/web-api/console/get-current-user/). If a user makes a request that requires an oauth token, a message will appear asking them to get an oauth token, so that case is handled. We'll continue to revise the usability of our developer tools going forward. Thanks so much for the feedback!
