### ISSUE TITLE
Response when relinking should not omit other markets the track is available in

### ISSUE THREAD

**Issue by rorygilchrist** [spotify/web-api#416]
When requesting a track for relinking, the payload should not omit the other markets that the instance of the track is available in.

Take for example, Run by Major Lazer. [When requesting the track ID: `0SujigeT7cxuxBfhN3eOcp` without the market parameter](https://developer.spotify.com/web-api/console/get-track?id=0SujigeT7cxuxBfhN3eOcp)) I get the available markets as `"available_markets" : [ "CA", "MX", "US" ]`. 

[When running the same request with `?market=US`](https://developer.spotify.com/web-api/console/get-track?id=0SujigeT7cxuxBfhN3eOcp&market=US), the `available_markets` field in the response is absent. Why not detail that it is also available in MX & CA?

**Comment by hughrawlinson** [comment]
Thanks for raising this question! I'll pass it on to the relevant team and get back to you.

**Comment by bih** [comment]
Hello @rorygilchrist,

Thanks for your suggestion! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, it was an intentional technical implementation. If you don't provide a market, we display all the `available_markets. If you provide a market, you know it is available in that particular market. For that reason I'm going to close this as <kbd>wontfix</kbd>.

Though I encourage you and other developers to continue to share use cases and support for this suggestion - it helps us prioritize in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍
