### ISSUE TITLE
add track to a collaborative playlist

### ISSUE THREAD

**Issue by Deskjet2526** [spotify/web-api#418]
Hello

I need add tracks to my collaborative playlist, on my web the users dont login and the playlist is mine i've create
can create a authorization code from my account(the account with the playlist)?
in my web the users(dont logged) can search tracks and add it to my collaborative playlist but always response this { "error" : { "status" : 403, "message" : "This request requires user authentication." } }

thanks

**Comment by hughrawlinson** [comment]
Hey @Deskjet2526 - in order to add a track to a playlist, the request must provide an auth token with the correct granted permissions from a user using either the `implicit grant` or `authorization code` flows. You could certainly use a token you've created from your own account - I'd urge you to be extremely cautious with this approach, make sure the token only has the minimum required scopes, and be aware while coding that if a third party were to discover this token or exploit a vulnerability in your code, they could change playlist data in your account.
