### ISSUE TITLE
do objects always contains all the keys ?

### ISSUE THREAD

**Issue by hycday** [spotify/web-api#438]
When a search-item (/v1/search) is made and the tracks->items is not empty (i.e. we have some results), can we ALWAYS assume that : 

all the keys will be populated for all the results ? or should we check that the value for specific keys are not empty and/or exists ?

With the same logic, when a get-track (/v1/tracks/) is made, can we ALWAYS assume that : 

the track->album->images array will contains the three size ( `height` = `640`, `height` = `300`, `height` = `64`) ?

**Comment by hughrawlinson** [comment]
Hi @hycday - In most cases, all keys should be populated for all results, but for various reasons this may not always be the case. We'll do our best to document these cases, but as they're usually a result of a bug, we won't be able to document them all. Because of this, I'd suggest that you handle key errors in your code. If for any reason our service returns a null value, you should handle the error so that your app doesn't crash or exhibit unexpected behaviour. Hope that helps!
