### ISSUE TITLE
Search for Playlist not returning own public playlist

### ISSUE THREAD

**Issue by rmmjohann** [spotify/web-api#447]
#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Call the `search` endpoint with `https://api.spotify.com/v1/search?type=playlist&query=name:Gemach`

#### Expected behaviour:
Result set contains my own public playlist "Gemach" https://open.spotify.com/user/1191223010/playlist/2RcuUkMZvA2YGr4ZGnhpwb

#### Actual behaviour:
empty result set

```
{
  playlists: {
    href: "https://api.spotify.com/v1/search?query=name%3AGemach&type=playlist&offset=0&limit=20",
    items: [ ],
    limit: 20,
    next: null,
    offset: 0,
    previous: null,
    total: 0
  }
}
```

**Comment by hughrawlinson** [comment]
Hey @rmmjohann, I've just asked the team responsible for this feature. I'll keep you up to date on this issue!

**Comment by hughrawlinson** [comment]
Hi @rmmjohann - this is happening because not all playlists are searchable. For optimization reasons, playlist searches are only run against playlists that meet certain criteria of usage. To provide search of a users own playlists, you should request all of the users playlists and do the search through the playlist titles in your application code.

**Comment by rmmjohann** [comment]
What are the criteria for public playlist searches? And what are the optimizations?
Can you provide information of the underlying database?
Why is there a feature for public playlist search, if one is not able to query them? And further it returns only 3k playlists as reported at #446

**Comment by hughrawlinson** [comment]
The criteria and optimisations are subject to change, so information about them and the underlying technology for our API isn't public.

You should view the search playlist functionality as a method to search active public playlists, rather than a mechanism to query the entire store of every public playlist on Spotify.

As I mentioned on #446, I'm in contact with the relevant team, and I'll keep you up to date on that issue.
