### ISSUE TITLE
Playlists Search returns a not found playlist

### ISSUE THREAD

**Issue by edwindayot** [spotify/web-api#45]
Issue found on 13 may 2015

Endpoints: 
- /search?limit=50&offset=50&q=portugal&type=playlist
- /users/glennpmcdonald/playlists/4imWYwhj7hNBqSrRgiPLpY/tracks?market=US

Actual behaviour: 404 Not Found

So I was trying to make a playlist about "portugal" using the PlaylistMiner. Using https://api.spotify.com/v1/search?limit=50&offset=50&q=portugal&type=playlist
The first issue was that this URL with this specific offset was returning a 500 error. Now, it's solved, but a new issue just appeared: using the URL https://api.spotify.com/v1/users/glennpmcdonald/playlists/4imWYwhj7hNBqSrRgiPLpY/tracks?market=US, which is a playlist fetched with the previous URL, a 404 was thrown. So I was thinking that, perhaps, the 500 was thrown because of this specific playlist. Hope it helps.

**Comment by thelinmichael** [comment]
Thanks for opening this issue @edwindayot. The 500 error was patched, but it was not related to non-existing playlists. 

My suspicion is that this is caused by the search index being out of sync with reality. This means that it currently takes a short while (not sure exactly how long, but not more than a couple of days.) for a removed playlist to be removed from the search index.

I'll follow up with some more information.

**Comment by thelinmichael** [comment]
Apologies for the late follow-up. The search index being out of sync with the playlist system was indeed the cause of this bug, but it's an extremely rare case since deleting a playlist from the system is basically the same thing as unfollowing it - it's still accessible if you've got the playlist's URI. This means that it has not _actually_ been deleted, just made inaccessible by obscurity. This playlist was removed in a way that isn't possible for non-employees, so this should theoretically never happen again.
