### ISSUE TITLE
How can I play songs on a mobile browser? 

### ISSUE THREAD

**Issue by Tzikas** [spotify/web-api#450]
I have a jQuery ajax call retrieving src links to certain songs and playing them fine on desktop, but I can't get them to play in a mobile browser.  Is there a way to do this?

**Comment by hughrawlinson** [comment]
Hey @Tzikas - where are you getting the src links from? Are you referring to the 30 second preview URLs? How are you playing them in the browser? Using the Web Audio API or an `<audio>` element?

**Comment by Tzikas** [comment]
Yes exactly. http://stackoverflow.com/questions/42829572/is-there-a-way-to-play-audio-on-a-mobile-browser-with-only-a-src-url

**Comment by hughrawlinson** [comment]
I've had a look at some of the usual issues related to this (audio can only be started in the mobile web in response to a user interaction event such as onclick, but I see you've taken that into account), but I can't find what the issue is. Have you tried remote debugging your app to see if any errors are being printed to the console?

**Comment by hughrawlinson** [comment]
I've copied my comment over to your stack overflow post, lets try and figure it out there? I'll close this issue.
