### ISSUE TITLE
Add the fields query parameter to other endpoints

### ISSUE THREAD

**Issue by blimmo** [spotify/web-api#486]
Currently the "Get a playlist's tracks" endpoint includes a fields query parameter that allows the user to specify certain information that they would like rather than retrieving everything. I think it would be useful to extend this functionality to similar endpoints such as the "Get a List of a User's Playlists" endpoint. 

An example use case might be a third-party app that needs to do some processing on one of a user's playlists. They could show a dropdown with the names of the playlists and have the URIs stored.

This is currently achievable with the current web API but it involves retrieving large amounts of data which are just ignored. The existing fields syntax would work well as a way for the user to specify which data they would like.

**Comment by asmitter** [comment]
Hi @blimmo 
We have no plans to add fields support to any other endpoints, but we will consider how we can optimise data transfer in the future.
Thanks for the suggestion!

**Comment by kingosticks** [comment]
Any chance you have reconsidering this position? It would be very useful, those simplified playlist objects are still pretty big, especially when you often only want the name and URI. Since the public API doesn't include access to your websocket endpoint we don't have any event mechanism and it's expensive to keep fetching everything all the time (`max-age=0` obviously isn't helping things either).

Alternatively, if you are focused on how you can "optimise data transfer", can we get some kind of `snapshot_id` for the user's entire playlist container? That'd at least save multiple trips when the user has > 50 playlists.
