### ISSUE TITLE
Document what features are only available for premium users in the API calls

### ISSUE THREAD

**Issue by jdrake3** [spotify/web-api#494]
Issue found on April 21st 2017.

#### Endpoint(s):
* `All`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Documentation
2. Read any item requiring premium access, such as `Get a User’s Available Devices`

#### Expected behaviour:
See that the API will only return data for premium accounts, realize that the API is nearly useless for non-premium users, and give up on your pointless project.

#### Actual behaviour:
Read the API documentation for two days, search StackOverflow, and waste a morning working with WPF to find out that unless one is ready to pay for Spotify the API is effectively useless.

**Comment by jscholes** [comment]
The [Working With Web API Connect document](https://developer.spotify.com/web-api/working-with-connect/) states fairly clearly that:

> Premium Only
> You can only control devices that belong to premium Spotify users.

This is the very first point raised by the linked document, so the information hasn't been hidden away.  Additionally, the documentation for a number of endpoints (e.g. [Start/Resume a User's Playback](https://developer.spotify.com/web-api/start-a-users-playback/)) includes the following text in the "Response Format" section:

> If the user making the request is non-premium, a 403 FORBIDDEN response code will be returned.

Finally, all pages related to the new Spotify Connect endpoints come with the following notice:

> These endpoints are in Beta. While we encourage you to build with them, a situation may arise where we need to disable some or all of the functionality and/or change how they work without prior notice.

Therefore if you've found some endpoints which do not return the expected error codes for non-premium users, or some endpoint documentation which doesn't make this clear, perhaps you could raise those specific examples?  For instance the documentation for the [Get a User’s Available Devices](https://developer.spotify.com/web-api/get-a-users-available-devices/) endpoint that you mentioned indeed doesn't include any information about expected behaviour for non-premium users.

**Comment by jdrake3** [comment]
I was admittedly more frustrated than warranted, frustrated, given that I am enjoying ad supported radio, 

The fact that it is called out in another document, does not address the complaint. I managed to ferret out similar information regarding play back control listed via googling, too, but only after several attempts and digging through additional undifferentiated text.

Your​ quote about the 403 is true, but as it is the last, sentence in the final paragraph above the example, you can hopefully see how it cold be overlooked.

Note how obvious it is in your post.  Simply calling it out similarly in the methods' documentation would be helpful.

**Comment by asmitter** [comment]
It's a valid point that we could call it out more explicitly. I'll make sure we include it more prominently on the individual endpoint docs. 👍

**Comment by asmitter** [comment]
The documentation for each endpoint requiring a premium user has been updated.
