### ISSUE TITLE
List of Categories does not include all categories

### ISSUE THREAD

**Issue by VirUZI** [spotify/web-api#5]
The endpoint https://api.spotify.com/v1/browse/categories does not include all categories which are included in the application in the Browse section. For instance in Sweden the category Word exists in the client application but is not included in the response for either https://api.spotify.com/v1/browse/categories or https://api.spotify.com/v1/browse/categories?country=se.
However if you guess the id of the category it is possible to get the playlist in that category using https://api.spotify.com/v1/browse/categories/word/playlists?country=SE

The expected behaviour is that "/v1/browse/categories" should include all available categories.

**Comment by asmitter** [comment]
I've looked into this and "word" is the only category affected. This is due to regional availability of that category, and a fix is on the way.

**Comment by VirUZI** [comment]
I have also seen the same problem for the category "Inspirational" (which I believe is the same as Christan in the US). Will this be solved by the same fix or is that another problem?

**Comment by asmitter** [comment]
It's a generic fix not particular to "word", so I would imagine so.

**Comment by asmitter** [comment]
Had a further discussion around this and due to some nuances this isn't addressable at the moment, so for now I'm going to label it as a "won't fix" as it's not something we can actively work on.

I recommend using the list as returned, so that when this is resolved it will automatically start working and no code change is required to your app.
