### ISSUE TITLE
Want to display my own spotify recently played tracks on my personal website

### ISSUE THREAD

**Issue by mattyfresh** [spotify/web-api#505]
Was not sure where else to ask this question, but figured this was as good a place is any.

I am trying to figure out a way to display my own currently playing/last played Spotify tracks on my own portfolio website.  I see that the `/v1/me/player/currently-playing` endpoint requires me to be authenticated via the `Authorization Code Flow`.

My issue is I obviously don't want any real _logging in_ to happen, I simply want to display my own personal information on my website.

I see that there is a FAQ about this already here https://developer.spotify.com/web-api/authorization-guide/ at the bottom of the page, however I am having trouble wrapping my head around how I would obtain an Authorization Code (see https://developer.spotify.com/web-api/authorization-guide/#supported-authorization-flows **step 3**).

Is there a way for me to do what I want client side without having to actually go through the process of authorization (IE redirect user, have them click approve, redirect to a callback page with a `code=foobar` param)?  IE something like https://github.com/thelinmichael/spotify-web-api-node/blob/master/examples/access-token-using-client-credentials.js.  As far as I can tell I can't activate the proper scope permissions via the `client_credentials_flow`.

Again, my use case seems fairly straightforward, I figured there _must_ be some established pattern for doing this.

Thanks a bunch and let me know if I can provide any more clarity about my issue!

**Comment by jscholes** [comment]
As far as I know there's no way to accomplish this in a purely client-side way, because your access token *must* be included to identify you.  The very last thing you want to do is expose your own Spotify access token to the browser of everyone who visits your website.

My suggestion would be to set up a small API endpoint of your own - you could hack it together on your own server or a cloud platform like AWS Lambda, Google Cloud Endpoints etc.  All it would need to do is:

1. Fetch your access token from some secure server-side place and refresh it if necessary.
2. Fetch your recently played/currently playing data.
3. Optionally, clean up the data if you don't need all of it, so you're passing less data back to your visitors.
4. Return some JSON which some bit of JavaScript on your site can consume.

Some issues that spring to mind:

- If the API endpoint you set up can be accessed by a piece of JavaScript running in a client browser, then it can also be accessed directly by a user.  This might not be desirable, so you might want to render the list of tracks for display server-side as well.
- If your website gets some heavy traffic you might end up hitting the Spotify web API rate limits, so you should probably implement some sort of caching mechanism.

Seems like a lot of work I know, but none of the authorization flows were really designed for this; it would make it far too easy for someone to obtain your access token and use it to control your account.  Somebody else might have better news for you, though.

**Comment by mattyfresh** [comment]
Yeah I realized I was digging myself a hole a few hours ago (I contemplated spinning up a little service on Heroku).  Instead, I decided to just turn on _scrobbling_ within Spotify and use LastFM's user endpoint to get my recently played track(s).  It's dead simple and only requires an API key.

In case anybody has the same or a similar use case:
http://www.last.fm/api

The only thing you I wanted that I could _not_ get was a link to an audio file, but I believe if your API key is associated with a premium account on LastFM there is a way to set up an audio stream.

Thanks so much for your response though @jscholes!  Feel like if anything I got a much better handle on the oAuth process for Spotify..

**Comment by hughrawlinson** [comment]
@mattyfresh as usual, @jscholes's reply was perfect - you would use the `/v1/me/player/recently-played` endpoint to get a list of up to 50 of your recently played tracks using an access token that is tied to your account. I'd recommend doing the authorization code flow to get a refresh token, and storing that on a server. You'd then expose an API on your server (heroku is a good shout!) that will when called fetch the recently played tracks from Spotify using an access token generated from your refresh token, and returning that.

Here's a reference implementation in Javascript (that you will definitely have to modify, but it's a good start)

```javascript
const fetch = require('node-fetch');
const express = require('express')
const app = express()

const spotifyAPIBaseUri = 'https://api.spotify.com'
const spotifyAccountsBaseUri = 'https://accounts.spotify.com'

const clientId = process.env['SPOTIFY_CLIENT_ID']
const clientSecret = process.env['SPOTIFY_CLIENT_SECRET']
const refreshToken = process.env['SPOTIFY_REFRESH_TOKEN']
let accessToken = '';

const refreshAccessToken = () => {
  return fetch(`${spotifyAccountsBaseUri}/api/token`, {
    method: 'POST',
    body: `grant_type=refresh&refresh_token=${refreshToken}`,
    headers: {
      'Authorization': `Basic ${new Buffer(`${clientId}:${clientSecret}`).toString('base64')}`
    }
  })
}

const getRecentlyPlayed = () => {
  return fetch(`${spotifyAPIBaseUri}/v1/me/player/recently-played`, {
    headers: {
      'Authorization': `Bearer ${accessToken}`
    }
  })
}

app.get('/my-recently-played', function (req, res) {
  getRecentlyPlayed()
    .then((recentlyPlayedResponse) => recentlyPlayedResponse.json())
    .then((recentlyPlayedResponseJSON) => {
      res.send(recentlyPlayedResponseJSON);
    })
    .catch(() => {
      refreshAccessToken()
        .then((refreshResponse) => response.json())
        .then((refreshResponseJSON) => {
          accessToken = refreshResponseJSON['access_token'];
          getRecentlyPlayed()
            .then((recentlyPlayedResponse) => recentlyPlayedResponse.json())
            .then((recentlyPlayedResponseJSON) => {
              res.send(recentlyPlayedResponseJSON)
            })
            .catch(() => {
              res.status(500).send('Failed to get recently played tracks');
            })
        })
        .catch(() => {
          res.status(500).send('Failed to refresh Spotify token')
        })
    })
})

app.listen(3000)
```
