### ISSUE TITLE
Trackset / Play Button issue

### ISSUE THREAD

**Issue by Bugs1012** [spotify/web-api#511]
The Spotify Play Button appears to have stopped working with trackset.  It will play the first track, but no others.  The documentation on the developer website no longer seems to mention it.  Has this feature been removed?  Is there another way to link tracks together in the play button?

**Comment by 72lions** [comment]
@Bugs1012 this feature has been removed. We have no support for it in the major clients anymore either. Another way to link tracks together is to create a playlist and add them there.

If it's ok with you, we will close this issue since it is not related to the web-api but to our Spotify Play Button.

**Comment by hubgit** [comment]
@72lions That's such a shame, this was a great feature - I don't think it's possible to create a temporary playlist in the same way?

Where would be a good place to ask for the Play Button to re-add support for this feature?
