### ISSUE TITLE
/v1/me/player API some times does not work without device_id and the documentation mixes POST and PUT

### ISSUE THREAD

**Issue by olejon** [spotify/web-api#523]
#### /v1/me/player API some times does not work without device_id and the documentation mixes POST and PUT

Issue found on May 11th 2017.

#### Endpoint(s):
* `POST /v1/me/player/next`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
1. Open documentation for `/v1/me/player/next`. It uses PUT in the cURL example, while it should use POST
2. Open the API Console
3. Get token
4. `/v1/me/player/devices` says only one device is active
5. Running `POST /v1/me/player/next` with Authorization but without `device_id` does does not always work with just one device active

#### Expected behaviour:
Endpoint should work with one device only without `device_id`

#### Actual behaviour:
Nothing happens to playback.

**Also, I have a question:** If several devices have Spotify open, which will be chosen by default without `device_id`?

**Comment by lrholmes** [comment]
I've been spending a lot of time with the Player API so I think I can help you out.

It says only one device is active because there can only be one 'active' device at a time - this is the device that should start playing when you post `/play` without a `device_id`. 
I've had the problem where music wouldn't play as well, and this was due to there being devices available, but none of them were "active". So make sure there is an active device, and if there isn't either transfer playback to it using [put-user-player](https://developer.spotify.com/web-api/console/put-user-player/) or provide the `device_id` of the device you want to play on.

Hope this helps.

**Comment by olejon** [comment]
Thanks. I've had no problems with the API after failure in the beginning. The documentation still needs to be updated and improved though. Also it is disappointing that all of the endpoints require Premium. Some of them shouldn't need to. Do you know by any chance if one can authorize if not a Premium user and one of the device APIs are in the scopes?

**Comment by lrholmes** [comment]
Nope, the whole Player API is premium only for now as far as I'm aware.

Don't forget that these endpoints are in beta though, so it's possible that with time the API will be relaxed to allow some of the endpoints for non-premium users.

Same goes for documentation - best thing you can do is let them know about the issues as you have. I for one am pretty glad that they decided to make the API available despite it not being 100% perfectly documented, just means we got it early instead of having to wait a while longer.

**Comment by olejon** [comment]
I agree on that. So I have to make two auth options, scopes for Premium users and those who are not? Would be nice if it returned a token even though not Premium, just that the endpoints won't work of course. My app already knows if the user is Premium using the profile endpoint.

**Comment by lrholmes** [comment]
Oh sorry, I misread your question. You will not need to have two auth options. The only difference will be that if you make a request to the player api as a non-premium user, you'll get a `403 FORBIDDEN` response. I recommend that you make a secondary non-premium account to have a go!

**Comment by olejon** [comment]
Thanks, just needed to know that. Have a OAuth solution for my app that has been working for years and just added the scopes and suddenly worried if new users that don't have Premium will not be able to authenticate. I probably have another user somewhere, if so it's written down in my docs, I'm just on my phone now. No worries then if you're right. My app checks if the user is Premium after authentication and stores it and uses it to enable features like these if Premium.

**Comment by lrholmes** [comment]
Sounds like you're doing it the right way 👍 

Good luck with the app!

**Comment by olejon** [comment]
Thanks!

**Comment by asmitter** [comment]
It sounds like you've got things working (great job, @lrholmes!) so I'll close this issue.
Additionally, I looked into your note that the docs mix up POST and PUT. Turns out the "Skip Next" console page (POST) was linking to the "Pause Playback" docs (PUT). I've corrected the link.
Please let us know if you have further issues with either the APIs or the docs.
