### ISSUE TITLE
Artist album listing does not include all albums

### ISSUE THREAD

**Issue by dsoprea** [spotify/web-api#528]
#### Endpoint(s):
* `GET /v1/artists/<artist ID>/albums`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:

Use API console to get a listing of albums for "3 Doors Down". Example:

curl -s -X GET "https://api.spotify.com/v1/artists/2RTUTCvo6onsAnheUk3aL9/albums" -H "Accept: application/json" -H "Authorization: Bearer [access token here]"

#### Expected behaviour:
The same list of albums as in the application.

#### Actual behaviour:
Many duplicate albums (identical names, different IDs). "Away From the Sun" album missing even though shown in main application.

**Comment by jscholes** [comment]
You're most likely seeing duplicate items because of different market availability.  For example, the album "Us And The Night" has one release (spotify:album:3opqVXEveZ5BOeMq0tS9EF) which is available in 57 markets but they do not include Canada, Mexico or the USA.  Therefore, listeners in those markets will need to play the second version (spotify:album:01zrTZowtMtqYutWzzDgds) which has "CA", "MX" and "US" listed as its markets.

You can avoid this issue by including the market query string parameter when performing a search or looking up an artist's albums.  Either set it to a valid country code, or the string "from_token" which will take the correct market from the authenticated user's profile and only show content which is available to play in their country.

Hope that helps!  As a further tip, your original comment has been edited, but in the future, don't include your access token when reporting issues or code in a public forum such as GitHub.  The token does expire after an hour, but that gives someone plenty of time to access and modify your account using it.

**Comment by jscholes** [comment]
Update: I only just saw the end of your report - the album "Away From The Sun" is only missing because you're fetching a limited number of results (20 which is the default).  Either increase the limit (50 is the maximum allowed) or access the next 20 results by using the offset parameter.  Without a market specified, the total albums for this artist is shown as 105, so even if you set the limit to 50 you'll need to perform 3 API requests to fetch them all.  With the market parameter set to "US", that total drops to 19.

**Comment by arirawr** [comment]
@jscholes answer is correct. I'm going to close this issue. Good luck with your implementation!

**Comment by dsoprea** [comment]
I had inadvertently disregarded/forgotten the offset/count parameters because I had expected that, if it paged, it'd be similar to the search API, where a page-token is returned. Plus, in the Go implementation these parameters aren't exposed in the simple album-lister method. You have to use the method that takes the additional options.

Thanks for both answers. I implemented both this morning. Looks good.
