### ISSUE TITLE
available markets not up to date?

### ISSUE THREAD

**Issue by digitaldesaster** [spotify/web-api#53]
Hi, i have tried to filter out songs that are not available in my country ("DE" - Germany)

"Top 100 tracks currently on Spotify"
spotify:user:spotify:playlist:4hOKQuZbraPDIfaGbM3lKI

24 tracks are not available in Germany due to the api result, here are 3 examples.

all 3 are playable in Germany, so i guess the data from this call is not correct/ up to date.

Lean On (feat. MØ & DJ Snake)
Major Lazer
[HK, MY, PH, SG, TW]
http://i.imgur.com/J20HqbO.png

Sugar
Maroon 5
[]
http://i.imgur.com/tQNk1Zh.png

Are You with Me - Radio Edit
Frequencies
DK, FI, IS, NO, SE]
http://i.imgur.com/TbNyGXl.png

**Comment by JMPerez** [comment]
@digitaldesaster They might be playable because they are [linked to tracks](https://developer.spotify.com/web-api/track-relinking-guide/) that are playable in Germany.

Take "Lean On (feat. MØ & DJ Snake)" as an example. You can get its data making a request to https://api.spotify.com/v1/tracks/1qE47wUKG2juJwPoLqg4C9

If you pass the `market` parameter it will return a playable linked track if any:
https://api.spotify.com/v1/tracks/1qE47wUKG2juJwPoLqg4C9?market=DE (this returns spotify:track: 0BF6mdNROWgYo3O3mNGrBc as the playable linked track).

The [endpoint for getting a playlist](https://developer.spotify.com/web-api/get-playlist/) supports the `market` parameter too.

In the rest of them I suspect it happens something similar. It would be easier if the id of track was displayed in the screenshot, or if could paste it in the issue.

**Comment by digitaldesaster** [comment]
Thanks @JMPerez , this absolutely works well. the "is_playable" is perfect to filter the things out that cannot be played. one further question. The country code from Get Current User's Profile is "my market",  so i can use this to make the GetPlayListsTracks call, correct?

best regards

**Comment by JMPerez** [comment]
@digitaldesaster Yes, that is correct. If you are using the Get Current User's Profile endpoint you will have an access token that knows the user's country and you can send it to GetPlayListsTracks adding `market=from_token` in the call. 
From [the docs](https://developer.spotify.com/web-api/track-relinking-guide/):
>Valid market query parameter values are ISO 3166-1 alpha-2 codes, as well as from_token. If from_token is used, an access token tied to a user must be supplied; from_token is the same thing as setting the market parameter to the user’s country.

**Comment by digitaldesaster** [comment]
@JMPerez  thats great, just for my understanding the parameter for market must be "from_token" not the token itself ("A1B2C3D45...."). i think i have to read the whole documentation ;-) unitl now i cached the country code on login and always have to read it from sharedPrefs...

**Comment by JMPerez** [comment]
@digitaldesaster Yes, the parameter is `market=from_token` and then you pass the token in the `Authorization` header: `Authorization: Bearer <access_token>`.

**Comment by digitaldesaster** [comment]
@JMPerez ok, great. no i wonder if the android onPlaybackEvent shouldn't contain the new track not the old one. (playerState.trackUri) 

do i have top open a second ticket in the android thread?
thanks

**Comment by JMPerez** [comment]
@digitaldesaster As far as I know you need to pass whatever trackUri you want to play to the Android SDK, but you are in charge of obtaining a playable one, so you will need to make the request passing `market` and pass the trackUri to the SDK.

I recommend you use [Kaaes'](https://github.com/kaaes/spotify-web-api-android) Android wrapper if you want to make requests to the Web API from your android app.

**Comment by JMPerez** [comment]
@digitaldesaster I'm going to close this issue, as there wasn't any problem with the Web API after all. Thanks for the feedback and feel free to reopen it if you have more information to be added.
