### ISSUE TITLE
Get market of current user?

### ISSUE THREAD

**Issue by seahorsepip** [spotify/web-api#547]
I read about track relinking which is an awesome feature but I need a market id for that which isn't a problem but how do I actually get a market id for the current user? 

Currently I'm using the user his IP to get a country id but that's not always accurate in the case of travelling users as example, in those cases the market id doesn't change but the IP does.

**Comment by hughrawlinson** [comment]
Hi there @seahorsepip - you should use the "from_token" value for the market parameter. This will tell the API to get the correct market parameter for the user from their authentication token.

**Comment by ZinoKader** [comment]
I'd like to request this as a feature as sometimes you can't get around it. For instance, I am using the Spotify Android SDK and have a playlist where the host is playing the music using his Spotify account and the Spotify Android SDK - and others can search for and add music to that playlist which will eventually be played. Now, if the host and the other users are in different markets the users will be adding songs that can't be relinked nor removed because we have no idea what the host's market is. So in rare cases, the users will be adding songs to the playlist which the host cannot play.

**Comment by jscholes** [comment]
When you fetch the current user's profile via the [/v1/me endpoint](https://developer.spotify.com/web-api/get-current-users-profile/), the [user object](https://developer.spotify.com/web-api/object-model/#user-object-private) returned contains a "country" key.  The user will have needed to authorise your application using the [user-read-private scope](https://developer.spotify.com/web-api/using-scopes/).
