### ISSUE TITLE
Uniqueness of playlist_id

### ISSUE THREAD

**Issue by ncapdevi** [spotify/web-api#557]
I was hoping to get some clarification around the uniqueness of the playlist_id.  For example, [This playlist](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWZeKCadgRdKQ)  and [this playlist](https://open.spotify.com/user/spotify/playlist/2ujjMpFriZ2nayLmrD1Jgl) seem to point to the same playlist, but have different playlist_ids. Did the way that playlist_ids were generated change over time? Is there anyway to get all IDs that point to a specific playlist?

**Comment by hughrawlinson** [comment]
Hi @ncapdevi, Spotify operated playlists can move URI from time to time for various reasons, and old URIs may refer to the content in the new URI so that links don't stop working. Both URIs are valid. There's no way to get all the IDs that point to a playlist. Note that this will be very rare for playlists that aren't operated by Spotify.
