### ISSUE TITLE
Different number of results on /v1/search endpoint with Authorization Code and Client Credentials

### ISSUE THREAD

**Issue by chistaesse** [spotify/web-api#560]
Issue found on May 31th 2017.

#### Endpoint(s):
* `GET /v1/search/?type=track`

#### Scope(s):
* None

#### Steps to reproduce:
`q` parameter `Pearl J'ai des choses à te dire`

#### Expected behaviour:
With Authorization Code : there are 3 results
With Client Credentials : there are 2 results

**Comment by hughrawlinson** [comment]
Hi! Yes, this can happen because when an authorization code came from a user auth flow, search can be personalized. Hope that helps!

**Comment by chistaesse** [comment]
Hi,
with server-to-server, it's not possible to get the same results than authorization code ?
I quote your documentation "Only endpoints that do not access user information can be accessed", I thought `/v1/search` wasn't depend on "user information" but general.
Thanks

**Comment by hughrawlinson** [comment]
Hi @chistaesse :)

> with server-to-server, it's not possible to get the same results than authorization code ?

For the search endpoint, results for requests made using an auth token from the _client credentials_ flow can differ from the results for requests made using an auth token from the _authorization code_ flow. The reason for this is that auth tokens came from the authorization code flow specifically contain authorization for the user, so we personalize the results of the search. On the other hand, the _client credentials_ flow provides an auth token that contains no _user_ authorization, only _client_ authorization (think of the requests as being made on behalf of your app, instead of on behalf of a user). Requests made to the search endpoint with auth tokens that come from the client credentials flow cannot be personalized because the tokens don't relate to any user.

Of course, if you have done the authorization code flow (or the implicit grant flow) and have a token that is related to a user, you can make that request from either a backend or a frontend - anywhere as long as the token contains user authorization.

Hope that helps! Let me know if you have any questions.

**Comment by thomasmery** [comment]
Hi,

is this related to #568 ?

with a request made with the API console I get some results
none with the client credentials flow
for some requests

would it not be expected to be the contrary if the client credentials flow is not tied to a specifici user

thanks for any hep on this

I am ... confused
