### ISSUE TITLE
Category's for a Track/Album/Playlist

### ISSUE THREAD

**Issue by mhuusko5** [spotify/web-api#561]
Currently Album's expose a 'genres' list, but this is not particularly useful because there is no way (afaik) to find more content via the API based on genre; I expect that's not going to change anytime soon.

However Category's are a semantic/browsable element of the API, but have the problem of lack of transitivity - you can fetch categories and let the user browse manually, but you can't browse content in a Category based on an existing piece of content [that a user has/is interested in]. 

Tracks/albums/playlists exposing what Category's they belong too, would be a huge improvement in this regard.

**Comment by hughrawlinson** [comment]
Hi @mhuusko5 - there actually *is* a way to find more content based on the genre - the [recommendation API](https://developer.spotify.com/web-api/get-recommendations/). Here's a link to a request that (gets popular rock music](https://developer.spotify.com/web-api/console/get-recommendations/?min_popularity=1&seed_genres=rock).

Your request for a category endpoint for tracks/albums/playlists can't be done though - tracks/albums/playlists don't usually belong to a category because categories are (mostly) manually curated. Very few tracks/albums/playlists could have zero or more categories.

**Comment by mhuusko5** [comment]
Ah, great! Is there any plan to return human readable/localised names for the genre seeds/IDs returned by `/recommendations/available-genre-seeds`?
