### ISSUE TITLE
Increase in NULL `Preview_Url` on tracks?

### ISSUE THREAD

**Issue by scgough** [spotify/web-api#564]
I _feel_ like I'm seeing **a lot** more `null` values in the `preview_url` field when searching via the API or retrieving playlists via the API. 
Has something changed recently? Should I be concerned? (I understand some tracks just don't have previews but this seems to be a recent dramatic increase)

For example, `Katrina & The Waves - "Walking on Sunshine"` shows as available in the `available_markets` list but `preview_url` is `null`.

Also, when I search for `"Superunknown" by Soundgarden` none of the tracks on any version of the album (Super Deluxe, 20th Anniversary) seem to have previews?

Is the preview available only to Premium accounts in some cases? (I have a Basic account connected to the API in this case) 

Thanks for any light that can be cast onto this!

**Comment by hughrawlinson** [comment]
Hey @scgough - As documented, the preview URL can be null. This can happen for a variety of reasons related to licensing restrictions or technology. Your app should handle the possibility that a clip is not available.

Some preview URLs are only accessible to premium users due to licensing restrictions. To be clear, as mentioned in our Developer Terms of Service, you should absolutely not present content from API responses for premium users to anyone other than the premium user - this includes track previews.

Hope that helps clarify 😄
