### ISSUE TITLE
API seems to return incomplete results

### ISSUE THREAD

**Issue by SergejFrank** [spotify/web-api#585]
I was using the API a while ago and it worked fine. Today i wanted to try it againg but it is responding me "incomplete" results. I expected it to response with the same songs/artists as the client software.

When i am searching for the Song "Songs für Liam" i am not getting the Artist Kraftklub 

Endpoint(s):
GET /v1/search

Expected behaviour:
A song from the Artist Kraftklub

**Comment by jscholes** [comment]
Are you specifying an appropriate value for the market query parameter when submitting your search request?  In order to retrieve the most relevant results, you should aim to specify the desired market wherever possible.  You can use the value "from_token" if the market should be inferred from the country listed on your Spotify account.

Example request: [GET /v1/search?q=%22Songs+f%C3%BCr+Liam%22&type=track&market=from_token&limit=50](https://developer.spotify.com/web-api/console/get-search-item?q=%22Songs+f%C3%BCr+Liam%22&limit=50&type=track&market=from_token)

I'm in the UK, so setting the market parameter to "from_token" automatically infers that only tracks playable in the market "GB" will be returned.  The first result is [Songs für Liam by Kraftklub](spotify:track:2isyujVLDSr4lYhIo7qCRw).

> I expected it to response with the same songs/artists as the client software.

Note that, when using the search endpoint, receiving results in the exact same order as they are displayed in the Spotify client software is not guaranteed.  You will receive the same results, but they may appear in a different order.

Hope that helps.

**Comment by arirawr** [comment]
Closing this issue as we haven't been able to reproduce the behaviour. Feel free to reopen with reproduction steps if you are still seeing the issue!
