### ISSUE TITLE
Specific, numeric limits of endpoints? (and specific amount of time for 'Retry-After')

### ISSUE THREAD

**Issue by djamrozik** [spotify/web-api#589]
I believe a similar issue has been brought up before (#116), however, I have been googling for quite a while and cannot find any numeric limit for reaching a numeric endpoint, or a numeric amount of time for the 'Retry-After' header.

I recognize that the [rate limiting](https://developer.spotify.com/web-api/user-guide/#rate-limiting) section states to use the 'Retry-After' header if the status code is 429, but my issue is that I don't know if my application would be able to scale and if it would break at a point. It feels pretty... uncertain.

I guess the solution is to brute force my application to see when it fails, but this seems inefficient, any ideas?

The web api is great by the way!, this is just something that would really help.

**Comment by hughrawlinson** [comment]
Hi! We don't provide any specific numbers for rate limits as we may need to change them at any time without notice, and need developers not to rely on hardcoded numbers. You should definitely use the Retry-After headers as the way to handle rate limits. I can assure you, they're very generous rate limits - you won't run into problems unless you're scaling to many many users (in which case you should talk to us, @SpotifyPlatform on Twitter, dm's are open, and we can try to support you), or you can make optimizations to your implementation (like using multi-get endpoints rather than single get endpoints).
