### ISSUE TITLE
As a user, I would like to begin playing a track at a specified time marker

### ISSUE THREAD

**Issue by HooHaa8384** [spotify/web-api#596]
Issue found on February 19th 2015.

#### Endpoint(s):
* `PUT v1/me/player/play`
* `PUT v1/me/player/seek`

#### Scope(s):
* user-modify-playback-state

#### Steps to reproduce:
I am building an app that will allow a user to begin playback at a desired point in a track.  Currently I am issuing a play, then immediately issuing a seek.  95% of the time I get the expected behavior.  However, 5% of the time the seek is not executed. 

#### Expected behaviour:
Be able to issue a play and seek in the same command

**Comment by hughrawlinson** [comment]
Thanks for the feature request! Currently the best way to do this is the way you've described. You may get more success if you delay your seek call by as little as 50ms, but we'll take the request and see what we can do :)

**Comment by UlysseM** [comment]
I would love to have this feature as well.

Usecase:

The user may select a single track and perform seek on it (without context, passing only a single track in the "uris").

With the current implementation, I see two approaches:

* A simple one, (which always works, but produce jitter), consists in making a call to _play_ with the same _uris_, and on success, sends a seek operation. Works pretty well, but has a bit of latency, and I've had some case where I'd jump to the beginning of the track before jumping back to position I wanted to seek.

* The other one consists in just performing the _seek_, but I've found this quite problematic, as if my song reaches the end, seeking won't work. So to be "safe", I'd have to compute the time remaining on the track, which would require to know exactly the offset at which I am and the total duration of the track, and I'll also have to make sure I have at least a second or two remaining to send the seek, as an optimization, rather than just apply the first method.

Allowing to "seek" while doing a play would just be neat, no need to wait for the return of play to perform the seek, less jitter, less api call, everyone wins :)

**Comment by levin23** [comment]
HooHaa8384 any chance your app is complete or at least 'previewable'? I'd love to see and use it!

**Comment by FlorianLoch** [comment]
This would really be nice to have, it would also reduce the amount of requests sent to the API and would fit nicely into the options of initiating the playback ;)

**Comment by arirawr** [comment]
Hey everyone! I'm really happy to let you know that this is now available in the API! You can now pass a `position_ms` to the `/me/player/play` endpoint to start playback at that timestamp. You can see the updated documentation [here](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/).

Thank you for helping us make improvements to our platform! We hope you continue building great things 🎉 😄
