### ISSUE TITLE
Add support for collaborative playlists

### ISSUE THREAD

**Issue by triplef** [spotify/web-api#6]
We have many requests for this from our users.

**Comment by thelinmichael** [comment]
Thanks for the feedback @triplef. 

I'd like to add a disclaimer that although we do accept feature requests and feedback through Github, we can't give any promises that the features will be implemented either in the short term or long term. As I'm sure you understand this comes down to business priorities, legal issues, technical feasibility, and so on. 

Although I can imagine quite a lot of great use cases that support for collaborative playlists would enable, it's always appreciated if you could elaborate a bit about what you'd like to do if this feature was available.

**Comment by triplef** [comment]
Thanks @thelinmichael, totally understand.

Basically our users just expect to see to the same playlists they have in their Spotify app in our app, i.e. they see it as a bug that certain (collaborative) playlists are not visible in our app.

**Comment by viking2917** [comment]
There's any number of interesting kinds of content on the web, where a playlist embedded via the api onto the page would add value. Imagine a page about a hiking trail or a run, I'd like to invite my friends to come to that page and add tracks to a collaborative playlist for the hike (my spotify account would be the owner of that playlist). Building that playlist in the Spotify client loses all the context of the hike we're building the playlist for. It's not hard to imagine many other kinds of pages where a wiki-style playlist creation would make more sense on that page, instead of in the client. 

I'd turn it around and ask why this *isn't* allowed. It seems you've gone to some trouble to dis-allow it. But you can make it so users have to be authenticated before they add tracks. They could already do this in the Spotify client, so I don't see how this would introduce any new security concerns. And you'd get some great new playlists and sticky, contextually-relevant Spotify content into your system...

**Comment by thelinmichael** [comment]
You're right @viking2917, we've done additional work to exclude support collaborative playlists. One of the reasons behind this is the risk of abuse. As you probably know, Spotify playlists are either editable by one user or by all users - there's no concept of a specific set of users being allowed to modify a playlist. All that's needed to modify a collaborative playlist using any of the Spotify applications is the playlist's URI. This makes things a bit more difficult than it otherwise needed to be. I hope this gives enough insight to why working with collaborative playlists isn't supported just yet.

**Comment by triplef** [comment]
I should clarify that for our use case it would be sufficient to have read-only access to collaborative playlists. Is that something that could be supported as a first step?

**Comment by viking2917** [comment]
I guess I don't see why the risk of abuse is any worse via the API than it is on the Spotify client itself? Doesn't the user need to authenticate to Spotify either way? If the API (properly authenticated to a Spotify user) were allowed to modify a playlist, how could it modify the playlist in a way a user in the app couldn't? I suppose there's a volume question (API could add more tracks quickly than a human), but perhaps that could be addressed via a simple rate limit? Anyway thanks for sharing the underlying concern, much appreciated!

**Comment by samzscott** [comment]
+1

**Comment by Ricehigh** [comment]
Read-only access would go a long way! Please consider adding this.

**Comment by JMPerez** [comment]
Read access for collaborative playlists has just been added. In order to have access to them, you need to ask permission for the `playlist-read-collaborative` [scope](https://developer.spotify.com/web-api/using-scopes/#list-of-scopes).

Thus, an app will be able to read a user's collaborative playlists. In order to make changes to it you will either need the `playlist-modify-public` or `playlist-modify-private` scopes, depending on the playlist visibility. These scopes must be granted by the owner of the collaborative playlist, otherwise the modification will fail.

We have also updated the [Working With Playlists guide](https://developer.spotify.com/web-api/working-with-playlists/) to include this change.

**Comment by viking2917** [comment]
Just to clarify, the api now allows read-only access to collaborative playlists correct? Or can mods be made? (the note about playlist-modify-public suggests maybe users can edit the playlist through the api as well?)

**Comment by thelinmichael** [comment]
@viking2917, collaborative playlists can be read by all users given that they've got the Spotify URI for it. To retrieve a user's collaborative playlists, the application needs to use the [Get a List of a User's Playlists](https://developer.spotify.com/web-api/get-list-users-playlists/) endpoint with an access token with the `playlist-read-collaborative` scope authorized by the user.

Modifications to collaborative playlists can be done by the playlist's owner given that the application has been given `playlist-modify-private` scope. (Collaborative playlists are always private.)

The part about collaborative playlists that admittedly are a bit confusing, is that you need `playlist-read-collaborative` scope to include collaborative playlists in the user's list of playlists, but there's no `playlist-modify-collaborative` scope to modify them. Instead, modification only uses the `playlist-modify-private` and `playlist-modify-public` scopes.

**Comment by viking2917** [comment]
Thanks. It is confusing ("collaborative playlists can be read by all users given that they've got the Spotify URI for it. " and "Collaborative playlists are always private." also seems contradictory), but I think I understand. Thanks!

**Comment by thelinmichael** [comment]
All playlists can be accessed if you know the playlist's URI using the Web API, which is the same behaviour as in the Spotify applications on desktop and mobile. My point was that even collaborative playlists are accessible by any user if they have the URI. 

Collaborative playlists are however always hidden. If you have a public playlist and turn it collaborative, it'll automatically be set to private.

I will look at the documentation again to see if this can be clarified further.

**Comment by viking2917** [comment]
got it, thanks, that clarifies.
