### ISSUE TITLE
Track matcher

### ISSUE THREAD

**Issue by Jamie0** [spotify/web-api#608]
I'd love to see an API feature, similar to that of MusixMatch, which is essentially a search that is enhanced for track matching. They have a "matcher" that hits our use case bang on, but their database is wildly inaccurate (about 10% of the song titles are wrong, and they do not provide a way to correct it) which makes the data largely unusable.

The current search endpoint sort of allows you to include title and artist, but the artist field is very unforgiving to small differences. For instance, if the artist field contains "feat" or "ft" (which is perfectly normal in lots of ID3/etc. tags) then you get no search results. 

If you don't use the track/artist tags, then the search results become less accurate, and in my use case this is not ideal. 

My use case is to be able to automatically tag music files with a Spotify ID. It would be nice if the response also gave an accuracy score. 

Cheers guys!

**Comment by hughrawlinson** [comment]
Hi @Jamie0 - this seems like a particularly broad feature request, do you have any more specific ideas about what we could do to improve our search functionality?

**Comment by bih** [comment]
Hello [NAME],

As per [our new developer support process](https://github.com/spotify/web-api), we are closing tickets that require more information but have been inactive for an extended period of time. I'll go ahead and close this as <kbd>inactive</kbd>.

Of course, if you'd like to bring up this suggestion again, feel free to create a new issue! Otherwise, if we have anything related to this to share, we will post it here for your convenience!

Cheers 👍
