### ISSUE TITLE
me/following - ETAG value changes with every request

### ISSUE THREAD

**Issue by michaelherger** [spotify/web-api#609]
Title: me/following - ETAG value changes with every request

Issue found on July 11th 2017.

* `GET /v1/me/following`

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-following` endpoint

#### Expected behaviour:
The ETAG header should not change, unless the user's collection has changed.

#### Actual behaviour:
ETAG changes with every request.

**Comment by arirawr** [comment]
Hey @michaelherger, 

I looked into this for you. If you take a look in the API Console, you'll see that the response includes lots of data about each artist, including the number of followers they have. As you can imagine, that number updates relatively frequently!

I've been able to verify that the ETAG value doesn't change every time, but that if something changes in the response (ie. one of the artist's follower count changes), the ETAG will change.

This is expected behaviour, so I'm going to close this issue.

**Comment by mherger** [comment]
Ok, that makes sense _technically_. But from the user's point of view it doesn't. His list of followed artists didn't change. Maybe in this case there should be a lighter version of the request only returning artist IDs, but not all of their data?
