### ISSUE TITLE
Album API fails past offset 100000

### ISSUE THREAD

**Issue by laran** [spotify/web-api#61]
I ran this query:
https://api.spotify.com/v1/search?query=year%3A2015-2016&offset=100000&limit=20&type=album

In the results it shows me that there are 355044 total records. Also, it gives me the next URL as the href below.

https://api.spotify.com/v1/search?query=year%3A2015-2016&offset=100020&limit=20&type=album

When I get that href though, I get a bad response and a 400 error.

What I expect would be a 200 response with 20 results. I would expect this to work all the way up to the 355044 results that the API tells me are available.

**Comment by thelinmichael** [comment]
Thanks for reporting @Iaran. I think the correct behaviour here should be that the API returns `400 Bad Request` instead of `200 OK` as it does today. We've also not documented that the maximum offset is `100000`. My opinion is that if you need to use an offset above `100000`, you definitely need to a better search query.

**Comment by laran** [comment]
Maybe you can help me to craft a better query then.

I want to find all albums with a release date within the next 30 days. I asked about this in a separate issue and was told to search albums with "year:2015-2016", then get the individual album records, and check the actual release date to see if the record matches. This requires iterating the collection of all albums with year:2015-2016.

I've read the search documentation here:
https://developer.spotify.com/web-api/search-item/

And, in fact, it suggests getting albums by year. There IS no finer granularity than year regarding time. Without a finer granularity I see no way to find albums released within the next 30 days other than iterating through all records.

Do you know a better way?

Thanks

**Comment by thelinmichael** [comment]
If you wanted to, you could always grab search results alphabetically, e.g. 

- `https://api.spotify.com/v1/search?type=album&q=a+year:2015-2016` (~12500 results.)
- `https://api.spotify.com/v1/search?type=album&q=b+year:2015-2016` 

I think this highlights that the API needs to support this use case in a much more efficient way than forcing developers to iterate through results very inefficiently.

We've updated the documentation for the [Search endpoint](https://developer.spotify.com/web-api/search-item/) stating that the maximum offset is `100000`.

**Comment by laran** [comment]
That's helpful Michael. Thank you for updating the docs and for the suggestion to grab results alphabetically. That should help quite a bit!

I think that higher search specificity, especially over larger collections is needed for more efficiency. But I think I've got what I need for now. Thank you!

**Comment by davejhahn** [comment]
> If you wanted to, you could always grab search results alphabetically, e.g.
> 
> * `https://api.spotify.com/v1/search?type=album&q=a+year:2015-2016` (~12500 results.)
> * `https://api.spotify.com/v1/search?type=album&q=b+year:2015-2016`
> 
> I think this highlights that the API needs to support this use case in a much more efficient way than forcing developers to iterate through results very inefficiently.
> 
> We've updated the documentation for the [Search endpoint](https://developer.spotify.com/web-api/search-item/) stating that the maximum offset is `100000`.



> If you wanted to, you could always grab search results alphabetically, e.g.
> 
> * `https://api.spotify.com/v1/search?type=album&q=a+year:2015-2016` (~12500 results.)
> * `https://api.spotify.com/v1/search?type=album&q=b+year:2015-2016`
> 
> I think this highlights that the API needs to support this use case in a much more efficient way than forcing developers to iterate through results very inefficiently.
> 
> We've updated the documentation for the [Search endpoint](https://developer.spotify.com/web-api/search-item/) stating that the maximum offset is `100000`.

This does not return the expected results.  For example. for 2019, as of right now, there are 2421 albums that have "A" in the title (I know because I ran the full search with 2019-2019 and determined the count of the results with "A" in the title), however, if you query for "A" and 2019-2019, it returns 148.

148 total:
https://api.spotify.com/v1/search?q=a+year:2019-2019&type=album

It appears that search doesn't simply return all results with the letter "A" in it.  The documentation for search isn't very good, so it may be that something else needs to be done.

This to me means that there is no way, as of today, with the offset limitation of 10,000, to get the proper list of new releases after the total reaches 10,0000.

**Comment by shillshocked** [comment]
Right now it's at 10,000 only. Not enough for a year search.
