### ISSUE TITLE
Please add /me/artists endpoint

### ISSUE THREAD

**Issue by michaelherger** [spotify/web-api#611]
#### Endpoint(s):
* `GET /v1/me/following` would return the list of artists I follow. But the official Spotify applications would list the artists of albums in my library, too. Therefore I'd like to see a `/me/artists` endpoint which does return the same artists list as the official apps are showing.

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-following` endpoint

#### Expected behaviour:
Get the same artist list as when opening the official Spotify app

#### Actual behaviour:
I only get followed artists, but not those of whom I've added an album to my library

**Comment by hughrawlinson** [comment]
Hi @michaelherger - this behaviour allows us to more easily differentiate between artists that the user has followed, and artists whose albums the user has followed - as it's possible to relatively easily build the list as it is in the client using the [user's saved albums](https://developer.spotify.com/web-api/console/get-current-user-saved-albums/) endpoint, this feature is unlikely to get its own endpoint - but I'll keep this issue open so that it we can reconsider if it gathers support from the community.

**Comment by michaelherger** [comment]
I do see the flexibility. But one call giving me all results would save us developers the overhead of running different commands and consolidating results on the application side, as well as _save you_ the overhead of answering all those partially redundant queries.

**Comment by hughrawlinson** [comment]
Agreed - please feel free to keep this open, so that we can reconsider if it gathers more support from the community!

**Comment by jagrodal** [comment]
I also need this endpoint. Building the list from the saved albums endpoint takes too much time, since we only get 50 entries per query.

**Comment by bih** [comment]
Hello @michaelherger,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api), and given we have no plans to prioritise adding `GET /me/artists/` in the next 6 months, we will close this ticket as per our process.

Of course, if you have any additional cases and/or ideas to share, feel free to comment on this issue. Otherwise, we will post here if there are any updates relating to this request.

Cheers 👍
