### ISSUE TITLE
Recently Played Tracks endpoint doesn't return tracks when using before or after cursors.

### ISSUE THREAD

**Issue by gpsamson** [spotify/web-api#627]
Issue found on July 27th 2017.

#### Endpoint(s):
* `GET /v1/me/player/recently-played`

#### Scope(s):
* user-read-recently-played

#### Steps to reproduce:
1. Open the API Console
2. Call the `recently-played` endpoint with `limit` `25` and the `before` cursor `1498607705000`. The cursor timestamp is ~ a month ago.

#### Expected behaviour:
A list of track objects that were played before the timetamp `1498607705000`. Essentially, tracks that were played about a month ago. The track order isn't that importance since there is a played at timestamp, but preferably in chronological order.

#### Actual behaviour:
An empty list.

**Comment by jscholes** [comment]
As stated by the [docs for the Get Current User’s Recently Played Tracks endpoint](https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/):

> Returns the most recent 50 tracks played by a user.

In other words, this is a recently-played endpoint, not a generic playback history endpoint.  If the user has played 50 tracks since the timestamp given in your example, the expected result is to return nothing or, arguably, to throw an error.  There is currently no endpoint provided to retrieve a user's playback history for any given timestamp in the past.

**Comment by bih** [comment]
Hi @gpsamson,

The `GET /v1/me/player/recently-played` endpoint only displays the most recent 50 tracks, and if you provide a `before` cursor that is set to before the 50th most recent track, it is expected to provide an empty result.

As @jscholes mentioned, this is specifically a recently played tracks endpoint, not a generic play history endpoint. I'm going to close this issue for now, but let me know if you have any questions.

Cheers!
