### ISSUE TITLE
Artists Top Tracks - Limited or Paging?

### ISSUE THREAD

**Issue by scgough** [spotify/web-api#664]
Can the results from the Artists Top Tracks endpoint be paged or is this limited to a set amount of results? 

#### Endpoint(s):
* `GET https://api.spotify.com/v1/artists/{id}/top-tracks`

I note that only one page (containing 15 results in my test) was returned but can this be extended to return more tracks?

**Comment by jscholes** [comment]
This currently isn't possible.  The endpoint returns an array of [full track](https://developer.spotify.com/web-api/object-model/#track-object-full) object rather than a [cursor](https://developer.spotify.com/web-api/object-model/#cursor-object).  Notice that if you paste an artist URI into the Spotify desktop player, it will only show up to 10 top tracks.

**Comment by jscholes** [comment]
As an aside, the documentation for this endpoint confirms that the expected number of tracks is "up to 10", so if you're seeing more than that it sounds like a bug.

**Comment by scgough** [comment]
thanks for clarifying @jscholes 
appreciated 👍

**Comment by bih** [comment]
Hey! It has already been said by the awesome @jscholes, you shouldn't ever see more than 10 top tracks. This is also reflected on all of our apps too. I'm going to close this as it has been resolved 👍
