### ISSUE TITLE
Why does the Web Player return different search results versus the Search Web API?

### ISSUE THREAD

**Issue by jscholes** [spotify/web-api#667]
Issue found on September 19th 2017.

#### Endpoint(s):
* `GET /v1/search`

#### Scope(s):
* N/A

#### Steps to reproduce:
1. Carry out a standard search using the Web API, using a token granted to a third party application.
2. Perform the same search using the Spotify Web Player at open.spotify.com and observe the lists of tracks and albums (or capture the network traffic).

#### Expected behaviour:
The same search results for both clients, given that the Web Player is using the same Web API endpoint.

#### Actual behaviour:
The results shown in the Web Player are in a different order.  In most cases this seems quite arbitrary, although occasionally the Web Player seems to push regularly-listened tracks to the top of the list.

**Comment by bih** [comment]
Hey! The search results aren't specifically ordered. I tried searching on the Spotify Web Player versus searching through the API, and they have additional flags on their search results which looks like they influence the results themselves.

It looks like expected behaviour from our end. Is there anything in particular that you want from the Search API endpoint that we don't have already? Thanks!

**Comment by jscholes** [comment]
> they have additional flags on their search results which looks like they influence the results themselves.

Are you able to expand on this at all in terms of what sort of flags?

> Is there anything in particular that you want from the Search API endpoint that we don't have already?

Not really - just curiosity I suppose :) Thanks for the response!

**Comment by bih** [comment]
Hey @jscholes,

Sadly, I'm not able to expand on them. Anything we can share is documented on the [Spotify for Developers](https://developer.spotify.com) website. Otherwise, if I understand correctly, seems like this question is answered!

Let us know if I misunderstood or if you have any other questions! Cheers 👍
