### ISSUE TITLE
This API calls returns wrong albums for artist 5LHAS08dEYibJ7hlH9VOaP

### ISSUE THREAD

**Issue by TheMightyPope** [spotify/web-api#678]
Issue found on February 19th 2015.

#### Endpoint(s):
https://api.spotify.com/v1/artists/5LHAS08dEYibJ7hlH9VOaP/albums

#### Scope(s):
None (application is not using authentication)

#### Steps to reproduce:
Get a list of albums from the API call above.

#### Expected behaviour:
The last two albums retrieved are NOT from that artist

#### Actual behaviour:
The API calls returns albums related to two other artists at the end of the album list.

**Comment by arirawr** [comment]
Hi there!

I took a look at the artist you mentioned. It appears that the artist is featured on the last two albums, which is why they're returned by the endpoint.

![screen shot 2017-10-04 at 17 40 04](https://user-images.githubusercontent.com/6777313/31185056-5adcaab0-a92b-11e7-9a7c-d302e44591df.png)
![screen shot 2017-10-04 at 17 40 28](https://user-images.githubusercontent.com/6777313/31185055-5adb39f0-a92b-11e7-8c2e-78a5a07b717d.png)

This is expected behaviour for the endpoint. If you don't want albums like this to appear, you can set the `album_type` parameter to filter the response to not include albums on which the artist appears. Check out the documentation for that [here](https://developer.spotify.com/web-api/get-artists-albums/).
