### ISSUE TITLE
Request - ability to sort on 'Get Followed Artists' endpoint

### ISSUE THREAD

**Issue by tinyioda** [spotify/web-api#697]
Hey Everyone,

I'm looking to have something added to the endpoint: "https://api.spotify.com/v1/me/following"

I am able to pull the data correctly but there doesn't seem to be a logical sort order to the data. I'm trying to replicate the functionality in the Artists window in your client as part of my new web api implementation (https://www.nuget.org/packages/dotNETSpotifyWebAPI, one of the APIs listed on your website).

I suggest adding sorting options: Artist Name, Recently played/Accessed, Date/Time of follow
I'd also suggest adding a sort order: ascending, descending

Cheers!

Tinyioda

**Comment by jscholes** [comment]
Hi @tinyioda!  I don't work for Spotify or represent them in any way, but my assumption is that consumers of Web API data must take care of sorting that data themselves as desired.  If the Get Followed Artists endpoint was to offer sorting, then it would need to be added to plenty of other endpoints too, for example saved tracks and albums, playlists and playlist tracks, possibly even search results and more.

**Comment by tinyioda** [comment]
Hi @jscholes I don't disagree with anything you just said! (Maybe a first for the internet!)

The issue I have is that the results are not only 'unordered' but paged. Those two things don't make a lot of sense together and severely limit choices in UI design patterns.

For example: In developing my .NET wrapper for this library I also have a test media player (Xamarin Forms) that goes along side of it. I was working on implementing the Artists page as it's designed in the official client but ran into an issue that my call gets 20 (of the 191 artists I've followed). As I scroll down past the first 20, I make a call for the next twenty. Well now all of a sudden I have more artists that start with A popping up in the middle and the whole thing feels disjointed. The only way I can do client side sorting as you suggest is to call the API enough times to get all of my artists and then sort them and then bind them to the controls. This is obviously much slower, removes the snappy feel you're accustomed too in modern apps and on mobile makes requests for data much bigger.

I understand it would/could take a lot of work to modify this and the other endpoints but I think the benefits to the clients far outweigh that development time/effort.

**Comment by jscholes** [comment]
I completely understand where you're coming from.  Some suggestions which might help:

1. Rather than using the default limit of 20 artists, you can fetch up to 50 in one API call.  This takes your example of 191 artists down from 10 calls to 4 to retrieve the full list.
2. Combined with the limit increase, you can try fetching several pages in an asynchronous fashion, rather than sequentially one by one.
3. For a desktop or mobile application, have you considered fetching the user's followed artists in the background at application startup and then refreshing them periodically?  This would allow the user to see them instantly when needed, or at the very least would cut down on the amount of time they'd have to look at a "loading" icon or similar.

The last couple of suggestions above may cause you to run into issues relating to API rate limiting.  However, the followed artists endpoint supports caching via an etag.  Once you've fetched the initial list, store the etag value.  When refreshing the list later, send an If-Match header in the request, with its value set to the etag you previously saved.  If the list has been updated, you'll receive an HTTP/200 status code and can load the entire list again.  If not, you'll get a quick HTTP/304 response and don't need to bother.

Hope all that helps!  I know none of this is 100% ideal, but the only thing that would really fix it is a pushed status updates model from Spotify, rather than a pull-based HTTP API.

**Comment by tinyioda** [comment]
Wow that etag information is sorely lacking in the endpoint description (maybe that's the feature I should be asking for)! I will explore that immediately.

The example above was just that. I know I could bring down then number of calls or I could preload before anyone clicks on the Artists button. To me it just seems odd that these ideas _seem_ overlooked throughout the whole APIs design. I could be out to lunch but I would have started with filtering/sorting and worked backwards from there.

**Comment by 0xNF** [comment]
@jscholes 
> When refreshing the list later, send an If-Match header in the request, with its value set to the etag you previously saved

It should be noted that the [Spotify docs](https://github.com/spotify/web-api/issues/697) specify sending an `If-None-Match` header, as opposed to an `If-Match` header.

**Comment by jscholes** [comment]
@0xNF Many thanks for catching that!  I've updated my comment.

**Comment by arirawr** [comment]
Hi there! We don't have any plans to implement sorting on this endpoint, so I'm going to go ahead and close this issue. Looks like @jscholes has given some excellent tips on how to implement sorting in your app 🙂
