### ISSUE TITLE
Song count in Playlists

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/web-api#71]
There is a discrepancy between the number of tracks reported from the PC Spotify App, and what is reported by the Web API. I have also noticed that the Android Spotify App returns the same number as the Web API; so I am not sure where the problem is.

Look at the Afternoon Acoustic play list PC is saying 132 the others say 145.

I have just noticed a new playlist that I created which has 1 tracks in it is being reported by the web api as having 0 tracks; so I guess the web API is incorrect.

PC Screen Shot
![spotify_screenshot1](https://cloud.githubusercontent.com/assets/1115341/8245046/33555e00-166c-11e5-9cf6-4bd9cb33ecc8.png)

Android Spotify App Screen Shot
![spotify_screenshot2](https://cloud.githubusercontent.com/assets/1115341/8245052/497035fc-166c-11e5-838a-c97eff7f5865.png)

My Android App Screen Shot
![spotify_screenshot3](https://cloud.githubusercontent.com/assets/1115341/8245056/5696016c-166c-11e5-87f5-3ec24b27050d.png)

**Comment by thelinmichael** [comment]
Hi @Brad-Jackson, thanks for your report! I tried reproducing this, but was unable to do so as the desktop application shows 145 tracks in the [Afternoon Acoustic playlist](https://open.spotify.com/user/spotify/playlist/16BpjqQV1Ey0HeDueNDSYz), similarly to [the Web API](https://developer.spotify.com/web-api/console/get-playlist/?playlist_id=16BpjqQV1Ey0HeDueNDSYz&user_id=spotify). 

I suspect that the reason for this discrepancy is that your desktop application is set to hide unavailable tracks. You can toggle this in Preferences > Show Unavailable Tracks in Playlists. (For example, my desktop application shows 139 tracks instead of 145 in this playlist for my Swedish accounts when hiding unavailable tracks.)

**Comment by Brad-Jackson** [comment]
Hi thanks for the reply, yes you are correct the Desktop app did have the unavailable tracks hidden.
