### ISSUE TITLE
Add endpoint to like/dislike a track

### ISSUE THREAD

**Issue by seahorsepip** [spotify/web-api#710]
Right now there are no endpoints to like or dislike a track, but it's available on the official client while playing a Daily Mix.

Any chance there could be endpoints added to like or dislike a track?

Right now I'm using:

> PUT,DELETE https://api.spotify.com/v1/me/tracks

To add and remove a track to the songs library since it seems to have the same effect as liking and unliking a track.

But I'm still missing a way to dislike and undislike a track.

**Comment by arirawr** [comment]
Thanks for the feature request! We'll post here if there are any updates.

**Comment by lenisko** [comment]
Whole API section just for *Daily Mixes* would be great, they deserve it. I'm looking for this feature as well :smile: good work with other stuff~

Cheers!

**Comment by quillford** [comment]
+1. I'd like to use it for [https://github.com/quillford/gesture-remote](https://github.com/quillford/gesture-remote)

**Comment by lyrixx** [comment]
hello. I really need this feature too. Spotify keeps poprosing a very specific (and really really bad) artist. And I don't want it anymore

**Comment by pr1ntr** [comment]
This would be killer!

**Comment by krummler** [comment]
Definitely would love to see this!

**Comment by bih** [comment]
Hello all!

Thanks for your feature request! We're in the process of cleaning up our GitHub issue tracker (as per our [new developer support process](https://github.com/spotify/web-api)) to better serve you and other developers.

In this particular case, although this is a popular API request, we have decided to not prioritize this. Not having enough compelling use cases was part of that decision. For that reason I'm going to close this as <kbd>wontfix</kbd> for now.

I encourage you and other developers to continue to share use cases and support for this feature - it helps us prioritize features in the future. You should still be able to comment on this issue. We will post updates here if there are any updates relating to this ticket 🙂

Thank you for taking the time to share your feedback, and please continue to do so! We highly appreciate it and of course reach out if you have any other questions!

Cheers 👍

**Comment by alhockly** [comment]
I would still like to see this implemented for parity with mobile/desktop apps

**Comment by tejasvi** [comment]
I'm not sure of the internals but is it possible to fork and support like/dislike?

**Comment by seahorsepip** [comment]
> I'm not sure of the internals but is it possible to fork and support like/dislike?

No, the spotify web API is not something that is open source and/or you can host yourself, this GitHub repostory only contains very outdated API documentation and a readme that states that this repository is indeed only functions as a public issue trackers.

**Comment by gabriel-roth** [comment]
Now that Spotify has combined "liking" and "adding to library," the Library APIs effectively handle liking/disliking tracks and albums.

One annoying quirk: When you like an album using the API, every individual track on that album is also liked. This doesn't happen using the application.

**Comment by mySebbe** [comment]
> Now that Spotify has combined "liking" and "adding to library," the Library APIs effectively handle liking/disliking tracks and albums.

From what i see "Liked Songs" ist not a Playlist its a Library. So you are not right the api for "liking" is still missing.

**Comment by digitaldavenyc** [comment]
@bih Ok so I have a really good use case for why this feature is needed, without it, it's breaking Discovery Weekly for some users. We are creating playlists for users based on shows in their area, this is going to include a decent amount of artists users will NOT want to listen to. Because of this Spotify is creating Discover Weekly playlists that include a lot of unwanted artists. Here is a real world use case:

- User on our app create a Playlist based on Upcoming shows in their area.
- Our app connects to Spotify to create the playlist for 66 shows.
- We play the most popular track first and the Backstreet Boys are playing today.
- Users skips the first few backstreet boys tracks, they are not a fan.
- Discover Weekly starts including backstreet boys and similar bands to next week, user is very annoyed

This actually no negative impact on our app, it will be in the best interest of Spotify to include this. We would absolutely include it because we want our Users to have a good experience in our app and Spotify.

**Comment by jack1142** [comment]
For my use case, it would be nice to be able to be able to get information if the track is disliked. Currently because of simplification of "likes" to adding the song to library/liked songs checking if track is liked is possible through `/v1/me/tracks/contains` endpoint, but there's still no way to check if the user has disliked the song.
I am using Spotify API in my script to email me songs from old Discover Weekly at the end of the week so that I can look through songs that I didn't manage to like/dislike during the week. I don't want to waste time on looking again through songs that I disliked during the week or those that I already liked and added to some playlist. And whilst the latter is possible, the first is not and that really is a bummer considering that usually at least half of my Discover Weekly playlist's songs have a dislike.

**Comment by mgsloan** [comment]
These days the API does provide an easy way to do this - just a simple `PUT` request to `https://api.spotify.com/v1/me/tracks` as documented [here](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-save-tracks-user).  Unfortunately I have not found a way to flag tracks with "Not like"
