### ISSUE TITLE
403 - not allowed when modifying discover weekly to public

### ISSUE THREAD

**Issue by henrydeclety** [spotify/web-api#722]
Title: not allowed when modifying discover weekly to public

Issue found on November 16th 2017.

Endpoint(s):
* `PUT /v1/users/{user_id}/playlists/{playlist_id}`

Scope(s):
* playlist-modify-private streaming user-read-private playlist-read-private playlist-read-collaborative playlist-modify-public user-read-birthdate user-read-email

So basically I am able to modify the public property for many playlists but when I try set my 'Discover Weekly' to public I get an 403 - not allowed error. Precisely the endpoint I used was: https://api.spotify.com/v1/users/1142095940/playlists/37i9dQZEVXcEMfNZ9gNPY5

**Comment by arirawr** [comment]
Hey @henrydeclety - the Discover Weekly playlist is actually owned by the "Spotify" user, and not by you. You cannot modify playlists that you don't own via the API. 

I recommend making a copy of the DW playlist on your own user account, which you can do [via the API](https://developer.spotify.com/web-api/playlist-endpoints/).

**Comment by henrydeclety** [comment]
Hi @arirawr, thanks for your answer but I was modifying the 'Discover weekly' of the currently logged in user (owner of that playlist) with his token..

**Comment by henrydeclety** [comment]
For a given user I can modify all of his playlists public's property unless 'Discover weekly'

**Comment by jscholes** [comment]
Hey @henrydeclety - there's been some confusion here.  @arirawr pointed out that every Discover Weekly playlist is owned by the "Spotify" user, meaning a user account with the username of "Spotify" representing the Spotify service rather than the currently logged in user.  If you copy the Spotify URI for your Discover Weekly playlist, you'll notice that it looks like "spotify:user:spotify:playlist:xxxxxxxxxxxxxxxxxxxxxx.  The username is "spotify", not your own username.  Thus, the logged in user does not in fact own the Discover Weekly playlist and cannot modify its public status.
