### ISSUE TITLE
Play button on web embeds not consistently working

### ISSUE THREAD

**Issue by drazamilo** [spotify/web-api#736]
Issue found on February 19th 2015.

#### Endpoint(s):
* They're not really endpoints, they're the embeds.

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open Spotify on your computer
2. Press Log in with Spotify here: https://www.realtor.com/holiday-playlist/
3. Press the play button on any of the embeds

#### Expected behaviour:
It should play the song in the open Spotify player

#### Actual behaviour:
Nothing happens. This only happens is Spotify is already open when logging in. If Spotify is not already open, then it logs you in as expected and when you press the play button it opens the Spotify player and begins playing the song.

**Comment by bih** [comment]
First of all, happy new year @drazamilo!

Hmm, I can't seem to find any Spotify play widgets on that URL. Apologies for not reaching this in time, considering it was designed for the festive period that has just ended!

It's worth noting that you shouldn't need to log into Spotify through a third-party website in order to use the play widgets. They work separately from third-party app authentication.

As this issue is not reproducible, I'm going to respectfully close the issue. Feel absolutely free to re-open if you can provide another working example of this bug so we can try to reproduce it 👍
