### ISSUE TITLE
progress_ms : null for /v1/me/player/currently-playing

### ISSUE THREAD

**Issue by nicolasanjoran** [spotify/web-api#748]
Issue found on December 21st.

#### Endpoint(s):
* GET /v1/me/player/currently-playing

#### Scope(s):
* user-read-currently-playing

#### Steps to reproduce:
1. Open the API Console
2. Request a token with the `user-read-currently-playing` scope
3. Call the `currently-playing` endpoint while a song is playing from a Spotify app.
4. Skip to the next song from the Spotify App
5. Re-Call the `currently-playing` endpoint while the song is playing from a Spotify app.

#### Expected behaviour:
The progress_ms field contains the progress as an Integer
```
{
"progress_ms" : 99969,
"is_playing" : true
...
}
```

#### Actual behaviour:
The **progress_ms** is sometimes **null**
```
{
"progress_ms" : null,
"is_playing" : true
...
}
```

**Comment by arirawr** [comment]
Hi @nicolasanjoran - thanks for the report! As documented [here](https://beta.developer.spotify.com/documentation/web-api/reference/player/get-the-users-currently-playing-track/), `progress_ms` can sometimes be null (for various reasons), and your app should be able to handle null values for this field.

As this is expected behaviour, I'm going to close this issue.
