### ISSUE TITLE
I am not able to get past the endpoint v1/me (401 error).

### ISSUE THREAD

**Issue by abhi-jha** [spotify/web-api#806]
Issue found on February 28th 2018.

#### Endpoint(s):
* `GET /v1/me

#### Steps to reproduce:
1. Get a bearer token
2. Call the `https://api.spotify.com/v1/me` using that token

#### Expected behaviour:
A user object whose token is sent.

#### Actual behaviour:
401 Unauthorized (consistently)

NOTE: I am able to use some of the other end points using the token but when I try to access my profile it gives me a 401 error with the exact same token. I went back to my dashboard and there's not much settings left to be done that can make any big difference.

**Comment by jscholes** [comment]
> 1. Get a bearer token

Could you expand on this?  Which authorization flow are you using to obtain the token?  Only the Authorization Code and Implicit Grant flows allow you to fetch a user's personal data, so if you're using the Client Credentials flow the endpoint won't work.  Does the endpoint work if you obtain a token from the Web API Console and try it out there?

**Comment by arirawr** [comment]
Hi @abhi-jha - @jscholes is exactly right.

There are two types of access tokens: those granted by the application (Client Credentials Flow) and those granted by the user (Implicit Grant Flow or Authorization Code flow). Both types will work for things like Search, getting artists or tracks, etc, but you will need to use a user-granted token in order to get any user-specific data. You can read up on all three authentication flows here: https://beta.developer.spotify.com/documentation/general/guides/authorization-guide/
