### ISSUE TITLE
502 BadGateway for start/resume with URI offset on playlist

### ISSUE THREAD

**Issue by pardahlman** [spotify/web-api#815]
Issue found on 2018-03-18

#### Endpoint(s):
* `PUT /v1/me/player/play`

#### Scope(s):
* user-read-recently-played
* user-read-playback-state
* user-modify-playback-state

#### Steps to reproduce:
1. Query `v1/me/player/recently-played` to get a list of play history object. Find an object where `context` is of type `playlist`.
2. Make sure that the resource owner has an active device, then call `/v1/me/player/play` with `context_uri` from the play history object's `context.uri` property and `offset.uri` from `track.uri` 

Here's an example payload, constructed from a retrieved play history object which fails

```json
{
    "context_uri": "spotify:user:spotify:playlist:37i9dQZF1DXe2SymtxlfwF",
    "offset": {
        "uri": "spotify:track:34NxQx4hfkxIVBc3aapvJJ"
    }
}
```

However, if I change the `offset` to use a positional offset the request succeeds, but for the track corresponding to that offset. As the track in my example is from a playlist, there is no way for me to know the positional offset based on the play history object.

The `uri_offset` seems to work when the context is an album.

#### Expected behaviour:
Playback updated according to [the documentation](https://developer.spotify.com/web-api/start-a-users-playback/).

#### Actual behaviour:
If the device is unavailable, 202 Accepted (which is expected), otherwise 502 Server Error (consistently) with response body

```json
{
  "error": {
    "status": 502,
    "message": "Backend respond with 500"
  }
}
```

**Comment by arirawr** [comment]
Hi @pardahlman, thanks for the report.

I can't seem to replicate this.

You can confirm that the offset works with playlists by copying the following into the web api console here: https://beta.developer.spotify.com/console/put-play/

```
{
  "context_uri": "spotify:user:arirawr:playlist:1WzJK3mYKzz0AlFmUvsZaK",
  "offset": {
    "uri": "spotify:track:6Ac4NVYYl2U73QiTt11ZKd"
  }
}
```

I suspect your issue may be due to Track Relinking.
If you check out [this console response](https://beta.developer.spotify.com/console/get-track/?id=3Ne4AkxJXpDOzGG7Connkk&market=SE), you'll see that it actually returns a different ID than the one we requested, and includes the requested ID in the `linked_from` field. In your case, the track with the ID you are requesting is not actually the one in the playlist but one relinked from it. You can read up on how track relinking works here: https://beta.developer.spotify.com/documentation/general/guides/track-relinking-guide/

Hope that helps!
