### ISSUE TITLE
https://accounts.spotify.com/en/login throws js error

### ISSUE THREAD

**Issue by bucchere** [spotify/web-api#820]
Issue found on February 15th 2018.

#### Endpoint(s):
* `POST /en/login`

#### Scope(s):
* playlist-modify-public

#### Steps to reproduce:
1. Past this URL into a Firefox window or tab: https://accounts.spotify.com/authorize/?client_id=XYZ&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fcallback&scope=playlist-modify-public
1. Paste a valid `client_id` over `XYZ` 
1. Hit Enter
1. Open developer tools
1. Enter valid username/password
1. Hit Login

#### Expected behaviour:
Redirect to http://localhost:3000/callback with oauth params.

#### Actual behaviour:
Page does not respond when you click Login.

This error appears in the console:

```
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Y@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:5:6496
At@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:14454
Tt/<@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:14923
i@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:5:1295
Tt@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:14905
o@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:15632
s@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:7:2578
l/<@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:7:2750
$eval@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:7:10263
$digest@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:7:8767
$apply@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:7:10548
i@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:17511
m@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:19361
Ut/</$.onload@https://d2d1dxiu3v1f2i.cloudfront.net/75e1de4/js/index.js:6:19904
```

**Comment by bucchere** [comment]
It behaves similarly in Chrome. Oddly, this seemed to be working just a few days ago.

**Comment by 0xNF** [comment]
I've also been getting similar errors in mobile Firefox for iOS. 
The web login was fine, and now it is not. 
Meanwhile it works fine in desktop browsers.

**Comment by arirawr** [comment]
Hey @bucchere  - I haven't been able to replicate this. Could you paste the exact URL you're using, including client ID and redirect URI?

**Comment by hughrawlinson** [comment]
Hey @bucchere - we haven't been able to reproduce this issue, and haven't heard from you in a while, so we'll close this issue. Feel free to ping me with repro steps if this issue is ongoing for you!

**Comment by bucchere** [comment]
I can no longer reproduce this either. Thanks for looking into it.

**Comment by robertocg72** [comment]
Hello

I'm having exactly the same problem as @bucchere, ca someone re-open this issue or do I need to create a new one?

Thanks

**Comment by robertocg72** [comment]
Hello @arirawr , thanks for your reply

The URL is

https://accounts.spotify.com/en/authorize?response_type=token&client_id=MY_CLIENT_ID&redirect_uri=http:%2F%2Flocalhost:3000%2Fcallback.html&scope=user-read-private%20playlist-read-private

Do you need my client id? (Is it safe to make it public?)

In Firefox I get exactly the same error message as @bucchere above; in Chrome I get a few more errors BEFORE the Spotify exception, please see below:

Refused to load the image 'https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-5784146-31&cid=1808353561.1522163609&jid=675552814&_v=j66&z=1217555094' because it violates the following Content Security Policy directive: "img-src 'self' https://d2d1dxiu3v1f2i.cloudfront.net https://i.imgur.com https://d2mv8tnci56s9d.cloudfront.net https://profile-images.scdn.co https://aci.scdn.co https://graph.facebook.com https://fbcdn-profile-a.akamaihd.net https://scontent.xx.fbcdn.net https://www.google-analytics.com https://stats.g.doubleclick.net data: d2d1dxiu3v1f2i.cloudfront.net".
Refused to load the image 'https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-5784146-31&cid=1808353561.1522163609&jid=553074598&_v=j66&z=163511981' because it violates the following Content Security Policy directive: "img-src 'self' https://d2d1dxiu3v1f2i.cloudfront.net https://i.imgur.com https://d2mv8tnci56s9d.cloudfront.net https://profile-images.scdn.co https://aci.scdn.co https://graph.facebook.com https://fbcdn-profile-a.akamaihd.net https://scontent.xx.fbcdn.net https://www.google-analytics.com https://stats.g.doubleclick.net data: d2d1dxiu3v1f2i.cloudfront.net".

GET https://accounts.spotify.com/en/authorize?response_type=token&client_id=b158251ef81e470f9d5f5783bab97532&redirect_uri=http:%2F%2Flocalhost:3000%2Fcallback.html&scope=user-read-private%20playlist-read-private 400 (Bad Request)
(anonymous) @ index.js:6
y @ index.js:6
u @ index.js:6
s @ index.js:7
(anonymous) @ index.js:7
$eval @ index.js:7
$digest @ index.js:7
$apply @ index.js:7
i @ index.js:6
m @ index.js:6
$.onload @ index.js:6
load (async)
(anonymous) @ index.js:6
y @ index.js:6
u @ index.js:6
s @ index.js:7
(anonymous) @ index.js:7
$eval @ index.js:7
$digest @ index.js:7
$apply @ index.js:7
(anonymous) @ index.js:9
Je @ index.js:5
n @ index.js:5
index.js:6 SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Y (index.js:5)
    at At (index.js:6)
    at index.js:6
    at i (index.js:5)
    at Tt (index.js:6)
    at o (index.js:6)
    at s (index.js:7)
    at index.js:7
    at f.$eval (index.js:7)
(anonymous) @ index.js:6
(anonymous) @ index.js:6

**Comment by arirawr** [comment]
Looks like you're getting the error `INVALID_CLIENT: Invalid redirect URI`.

The redirect URI you use in your URL is `http://localhost:3000/callback.html`. You need to make sure that whatever URL you use is registered to your Client ID on your Spotify for Developers Dashboard (click the app then click Edit Settings). The URL there needs to be exactly the same as the one you use to authorize, right down to the trailing slash.

**Comment by robertocg72** [comment]
As you can see from the screenshot below, the callback URL is exactly the same as the one specified in the authorize request

![screenshot](https://user-images.githubusercontent.com/3854827/38548855-b55257ca-3caa-11e8-8ee8-bcfb16bcdec1.JPG)

**Comment by robertocg72** [comment]
Sorry, as i was pasting that image I realised I have a trailing character, let me fix that and retry

**Comment by robertocg72** [comment]
It's working now, sorry for not checking that carefully; thanks for your help!
