### ISSUE TITLE
Questions about commercial projects with Web-API

### ISSUE THREAD

**Issue by HwanChoi** [spotify/web-api#827]
We will provide Spotify app for our customer as additional service on our Hi-Fi devices.
According to the Spotify developer site, "This SDK must not be used in commercial projects without Spotify's prior written approval."
I'm wondering the commercial projects meaning.
Because We do not consider any profit model, we just show the sporty menu to the users on our digital audio player.
We do not consider any profit model, we just show the Spotify menu to the users on our digital audio player.
Therefore, We think it is not a commercial project. Is it correct? We asked the issue to Spotify via Application for Commercial Use but nobody answer.
So, please let us know that.

**Comment by 0xNF** [comment]
I am not a lawyer, so it's probably best to ignore me.   
That being said, unless you are giving away your Hi-Fi devices for free, it would seem to me that this would count as commercial use, because Spotify will become a feature that will help you sell your device.  
Deriving no profit from the integrations directly (i.e., you are not charging customers more money to access the feature) doesn't normally exempt one from a commercial use clause in other company's terms  if it's a feature of a product you _are_ deriving profit from.

**Comment by bih** [comment]
@HwanChoi Thanks for submitting an issue! Unfortunately, we can't give any advice on what is deemed to be a commercial project or not, and ask that you consult your own legal counsel on how your application fits within our [Developer Terms of Service](https://beta.developer.spotify.com/terms/).
