### ISSUE TITLE
Retrieve Current User's Followed Users' Currently Playing Track

### ISSUE THREAD

**Issue by hobbldygoop** [spotify/web-api#83]
It would be really useful to have a way to see what friends and followed people of a user are listening to right now, like the desktop client does in the right sidebar.

**Comment by BrandonSlaght** [comment]
+1

**Comment by sashaperigo** [comment]
+1

**Comment by danilocecilia** [comment]
+1

**Comment by kurtbradd** [comment]
+1

**Comment by wnvuong** [comment]
+1

**Comment by jolantz** [comment]
+1

**Comment by abunsen** [comment]
+1

**Comment by jonesnc** [comment]
+1

**Comment by CuBiC3D** [comment]
+1

**Comment by Qtrain** [comment]
+1

**Comment by owentdoyler** [comment]
+1

**Comment by Fiddlesteak** [comment]
+1

**Comment by drshrey** [comment]
+!

**Comment by frankolson** [comment]
+1

**Comment by ashley** [comment]
+1

**Comment by valiantone** [comment]
+1

**Comment by ctrezevant** [comment]
+1

**Comment by stephancill** [comment]
+1

**Comment by SemanticMike** [comment]
+1

**Comment by erorrov** [comment]
+1

**Comment by mpcathey** [comment]
+1

**Comment by gpranay4** [comment]
+1

**Comment by petonagy** [comment]
+1

**Comment by enisnazif** [comment]
+1

**Comment by Wake-Up-Donnie** [comment]
+1

**Comment by hughrawlinson** [comment]
Hey, update on this one - we won't implement it at the moment, because there's no mechanism for the users followed users to consent to letting your apps see what they're listening to. We're aware that it'd be a super useful endpoint for plenty of use cases, but our first priority is to handle our users and artists data responsibly and respectfully. If a convenient mechanism for facilitating this consent becomes available in a suitably frictionless manner in the future, we'll absolutely consider this.

**Comment by graham768** [comment]
Doesn't this mechanism already exist when a user confirms they want to publish their activity on Spotify or share activity on Facebook in the settings? I can already see the songs being listened to by people I follow. If they publish their activity to all of their followers and they don't have any control over who follows them, shouldn't this include third parties already?

**Comment by ctrezevant** [comment]
@graham768 raises a good point, but I think the distinction here is between an *application* having these permissions vs. a *user* who's viewing this information via the API. While it is true that a user has controls over what activity of theirs is publicly visible and where, there's no ability for users to distinguish these privacy controls between a third party application vs. someone that follows them (see below). 

<img width="805" alt="screen shot 2017-06-27 at 17 27 49" src="https://user-images.githubusercontent.com/7227500/27610924-3fa9e278-5b5e-11e7-9a9a-3b534dd58655.png">

That said, that wouldn't stop a determined third party from simply firing up [Charles](https://www.charlesproxy.com/) (or an equivalent) and simply watching traffic to discover the "secret" official endpoint for this, anyways. It follows that, if you're making your Spotify activity public, it's not hard to get ahold of. I think that it's important to decouple the reuse of publicly available information here- if you're explicitly consenting to making these details public, it would imply that you're also consenting to allowing others the ability to read and record that information. Otherwise, you wouldn't have turned that feature on in the first place. 

For many people (including myself), I think it would fit nicely into the current permissions model if it were possible to see the recent activity of friends I follow via the API, perhaps even with the contention that we must be mutual followers. For third-party applications requesting this functionality, this would be easy to include in [Spotify's OAuth scopes](https://developer.spotify.com/web-api/using-scopes/), satisfying the granular privacy controls being sought out here (as the user must explicitly grant those permissions to the application requesting them). 

Anyways, much love to the Spotify team!! You've built an amazing product. Hope to see this feature implemented one day, possibly:)

**Comment by sharkman** [comment]
Interestingly enough I've came to the api documentation just to find out there are no way to get user's friend's activity using the official api, despite the fact that the app itself shows that information.
I'll sub to this thread to watch on the updates.

Thanks,
Dmitry

**Comment by orenreu** [comment]
+1

**Comment by kayalardanmehmet** [comment]
+1

**Comment by maihe** [comment]
+1

**Comment by jakeduncan-roam** [comment]
+1

**Comment by jessety** [comment]
+1

**Comment by iremlaya** [comment]
+1

**Comment by Nosezeichen** [comment]
+1

**Comment by jsonpoindexter** [comment]
+1

**Comment by dandv** [comment]
If you're thinking to add "+1", please press +1 on the first comment instead.

**Comment by AdvaithD** [comment]
I've been looking around for this aswell. Any updates?

**Comment by andjelatomic** [comment]
I am also looking forward to this option. I've promised to my son that I'll make for him Pi or Arduino based device, with a small display, where he can see friend activity feed scrolling  (:  Probably I can make a list of a friends, and do it in a different way, but it will be nice to have it as already fine-tuned API.

**Comment by PeterShershov** [comment]
+ 1

**Comment by joosthoi1** [comment]
+1

**Comment by notserpp** [comment]
+1

**Comment by duttaditya18** [comment]
Would love to see this implemented. Several apps made using Spotify API would be able to utilize this.

It would open up a range of possibilities.

**Comment by SoundofColor** [comment]
Made an account so I could post that I, too, would love to hear if there are any updates to this!

**Comment by MattixNow** [comment]
+1

**Comment by KebapBoy** [comment]
This is the url the Spotify App uses to retrieve the data: [https://spclient.wg.spotify.com/presence-view/v1/buddylist](https://spclient.wg.spotify.com/presence-view/v1/buddylist)
But you will need a valid token issued for the Spotify App, web api tokens won't work.
Maybe someone can find out how to authenticate as Spotify App.

**Comment by leoforney** [comment]
+1

**Comment by SanJJ1** [comment]
Has anything else happened with this?

**Comment by mohit1337** [comment]
They should really give it by now, its been years.

**Comment by mohit1337** [comment]
> This is the url the Spotify App uses to retrieve the data: https://spclient.wg.spotify.com/presence-view/v1/buddylist
> But you will need a valid token issued for the Spotify App, web api tokens won't work.
> Maybe someone can find out how to authenticate as Spotify App.

How did you find this API? Probably same way API call to get app token can be found?
They should really give it by now, its been years.
