### ISSUE TITLE
Exposing p-line in both track and album endpoints

### ISSUE THREAD

**Issue by jolantz** [spotify/web-api#84]
It would be hugely helpful if you could expose the p-line on both tracks and albums. You should already have the info so it shouldn't be a huge thing. 

**Example of use case**
The Major Lazer album "Peace Is The Mission" has the p-line "© Mad Decent under exclusive license to Because Music". By exposing this, developers can use not only the release year info (which can be difficult to find) but also information about label, rep owner, licenses etc

Note that for this to work, it has to be exposes for both tracks and albums.

**Comment by thelinmichael** [comment]
Hi @jolantz! Thanks for getting in touch. Is there issue here that you want to avoid making a second request to the `/v1/albums/{id}` endpoint after retrieving metadata for a given track? The p-line is exposed as part of the `copyrights` property on the albums endpoint, and since it's not a track-specific property but rather an album-specific property, it makes more sense to only be part of the album object.

Example: https://api.spotify.com/v1/albums/1DKmAZJtbbpiBK1RftkHf4

Part of response:
```json
"copyrights" : [{
    "text": "(C) 2014 Universal Music AB",
    "type": "C"
  },
  {
    "text": "(P) 2014 Universal Music AB",
    "type": "P"
}]
```

Some of the p-lines are of course more verbose than this one.

**Comment by jolantz** [comment]
This would work for artist albums/single products, but I see two issues:

1. Tracks on compilations, best of-records and re-releases will potentially be tagged incorrectly as they might have been released earlier than the album product.
2. Minimize the number of requests.

You're right that p-line is mostly used for albums/products, but you should also receive p-line on track level.

**Comment by thelinmichael** [comment]
Hm. I'd still argue that the p-line belongs on the album.

If a track has been released several times, let's say once as part of a "regular" album, and once as part of a best of-record, there will have two separate track URIs, each pointing to the album it was released on, that each have their own p-line.

For example,
The album [Best Of](https://api.spotify.com/v1/albums/5wuDCQ0ETSqaYPRhFvoeDY) is part of The Cardigan's discography, containing the track Erase/Rewind. This track has the URI `spotify:track:6GnjOfq4MFPmDKkUV8zFD8`. The p-line for this album is `"(P) 2008 Universal Music AB"`.

Erase/Rewind was released on the album [Gran Turismo](https://api.spotify.com/v1/albums/6gxAs4Xk6dytHvqADOhLPw). However, on that album, the track has the URI `spotify:track:2UY4BdOZ7Ncfke96BBUTzM`. The p-line for the original album is `"(P) 1998 Universal Music AB"`.

It may seem unnecessary to use two different URIs for these tracks, but they may have differences in quality and metadata, and sometimes even content.

Regarding minimizing the number of requests, an alternative solution would be to include the [full Album object](https://developer.spotify.com/web-api/object-model/#album-object-full) in the [full Track object](https://developer.spotify.com/web-api/object-model/#track-object-full), instead of the [simple Album objects](https://developer.spotify.com/web-api/object-model/#album-object-simplified) which doesn't contain `copyrights`.

**Comment by jolantz** [comment]
An album p-line and a track p-line is two different things. I understand want you're saying but it's not a question of where the p-line belong, but that different p-lines are available on different "depths", ie album and track level. 

Take this example: I'm looking at a particular playlists and want to see what year the different tracks where released. If the playlist contains "Erase/Rewind" from the Best Of-album, the release year will come back as being 2000, from the album p-line, which is incorrect. Instead, if p-line was available on track level, the year would be 1998 (providing that the product is correctly set up). 

A good example would be Elvis Presley, for instance [The Definitive Collection] (https://open.spotify.com/album/7xzTrnYJPGfiVNT8MxaBK4). The p-line says 2006, but I can assure you that none of the tracks on that album is from that year. Exposing p-line also on track level would in this case be much more correct.

**Comment by arirawr** [comment]
Hey @jolantz,

As per our [new developer support process](https://github.com/spotify/web-api#creating-an-issue), any feature requests that have no plans to be considered in the next 6 months will be closed as wontfix.

We do not have any plans to implement this in the next 6 months and thus will close as wontfix.

We encourage you and other members of the community to continue to share use cases and your support for this feature, as it helps us prioritize features going forward. You will be able to comment on this issue even after it is closed. We will also post any updates here relating to this suggestion when they happen.
