### ISSUE TITLE
Web API to skip to next track?

### ISSUE THREAD

**Issue by chrisb2244** [spotify/web-api#85]
I can pause a track by sending (I don't know what) to 
\*.spotilocal.com:4371/remote/pause.json?pause=True\<extra\>
(or similar? Not that familiar with python, which is the language of the interface I'm using, and not at all familiar with JSON -> here, I think the \<extra\> would be something like "&oauth=<oauth-token>&csrf=<csrf-token>")

Likewise, ".../pause.json?pause=False\<whatever-else\>"  unpauses.

Is there a similar way to skip to the next song on a playlist? Reading the page linked on the web-api tracker homepage, to the spotify developers section, gives lots of links and examples to query user information, and so on, but nothing to control the movement of playing songs.

The 'Thirtifyer' example seemed hopeful, but the code there that contains the term "next" is completely different - I don't understand it at all.

**Comment by JMPerez** [comment]
What you are trying to do is managing the current queue / playback on your desktop client from a web app.

The Web API doesn't expose endpoints to do it, that's why you can't find it. The linked examples, like [Thirtify](http://lab.possan.se/thirtify/) use the 30 seconds audio previews for the playback, which happens on your browser and it's independent from what you are playing on your Spotify clients.

Spotify doesn't provide any official way to control the playback in the client from outside through HTTP calls, and even though there are some back-engineered implementations out there, they are not officially supported.
