### ISSUE TITLE
Adding artist social links to /v1/artists endpoint

### ISSUE THREAD

**Issue by david-mateos** [spotify/web-api#885]
Now that Instagram, Facebook, and Twitter links are available in the about section of artist profiles, will you please look into making that information available in the artist endpoint.

**Comment by bih** [comment]
Hello @david-mateos,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api), and given this particular suggestion has received no engagement for a while, I will close this ticket as <kbd>inactive</kbd>.

Of course, if you'd like to bring up this suggestion again, feel free to create a new issue! Otherwise, if we have anything related to this to share, we will post it here for your convenience!

Cheers 👍

**Comment by bulgariamitko** [comment]
6 months passes. Implement socials links as well, please!
