### ISSUE TITLE
Not asked to allow Scopes under certain circumstances during Authorization

### ISSUE THREAD

**Issue by dwo** [spotify/web-api#89]
This is not exactly easy to reproduce, but here is something we observed during the Authorization flow.

We had a user who created their Spotify account with an email and password, and later connected to Facebook.

The user was logged out of Spotify and Facebook when they went into the Authorization flow.

After logging into Facebook, the flow seemed to skip the step to ask the user to allow the requested Scopes. It went straight to returning an access token (which presumably wasn't permitted to make calls we wanted to make). When requesting the user's saved tracks (`/me/tracks`), we got back a successful but empty response.

When the user logged in manually via username and password instead, they got to the step to allow the Scopes and subsequent Web API calls for saved tracks returned non-empty successful responses as expected.

**Comment by thelinmichael** [comment]
Firstly, thanks for reporting this @dwo. 

> After logging into Facebook, the flow seemed to skip the step to ask the user to allow the requested Scopes. 

This is expected behaviour if the user has given the application permissions previously. If the application is requesting further permissions, the user has to give it authorization again though.

If I understand you correctly, the API treats this user as two separate users, depending on if they authenticate using Facebook login or if they use the login/password form. I've not been able to reproduce this issue with a test user, so if this occurs again, I'd really appreciate if you could make a request to the `https://api.spotify.com/v1/me` endpoint to retrieve the authenticated user's information when logged in using Facebook. You could also log in with the username/password and the Facebook profile on spotify.com and check the Account pages. 

I see two possibilities - either the internal 'connection' between usernames and Facebook profiles in Spotify has a bug, or the Facebook profile you're logging in with is connected to a different account than the one you're expecting.

**Comment by dwo** [comment]
I'll try and figure out if the second possibility is true and get back to you on this. :+1:

**Comment by thelinmichael** [comment]
Hey @dwo, I'm going to close this issue but don't hesitate to open it again if you believe there's a bug.
