### ISSUE TITLE
iFrame embed uri only playing preview in some browsers.

### ISSUE THREAD

**Issue by sCAIwalker** [spotify/web-api#916]
Issue found on February 19th 2015.

On my website, I can only seem to play previews of the tracks in the playlist in Chrome and Safari. However, the full tracks can be played in Firefox. Why might this be the case?

Here is my website : www.studify.online

#### Steps to reproduce:
1. Create an account and login
2. Click on "Music with background noise"
3. Select a playlist and play

#### Expected behaviour:
Widget is able to play full songs as user is logged in.

#### Actual behaviour:
Widget it only able to play previews of songs.

Here is an example url that one of my playlists is using. https://open.spotify.com/embed?uri=spotify:user:1276120884:playlist:3lupJoO6PjahRjP3ehIUpq"

EDIT : the entire track can be played in any browser when running on localhost, but cannot on heroku server.

**Comment by dforsyth-iit** [comment]
We're experiencing this issue as well, and it's impacting a client project. Any word on when this will be fixed?

**Comment by arirawr** [comment]
Hi @sCAIwalker - this is due to recent changes to the Spotify Play Button widget. You'll need to add `allow="encrypted-media"` to your embed code. You can read more in the blog post [here](https://developer.spotify.com/community/news/2018/07/19/new-updates-to-spotify-play-button/). Sorry that this wasn't documented sooner!
