### ISSUE TITLE
Multiple Field Filter's yielding no results

### ISSUE THREAD

**Issue by aeikenberry** [spotify/web-api#92]
In the docs (https://developer.spotify.com/web-api/search-item/) for Field Filters, it uses as an example query
 
    q=album:gold+artist:abba&type=album

but I'm not able to get this query to work. In the web api console:

<img width="831" alt="screen shot 2015-07-27 at 8 58 01 pm" src="https://cloud.githubusercontent.com/assets/599112/8921960/3cdd25b2-34a2-11e5-8836-ee2a6b71ae93.png">

<img width="869" alt="screen shot 2015-07-27 at 9 00 04 pm" src="https://cloud.githubusercontent.com/assets/599112/8921978/82da1200-34a2-11e5-8880-a380caf6254b.png">

Any tips for getting this to work?

**Comment by thelinmichael** [comment]
Thanks for bringing this up @aeikenberry. I believe this is caused by a bug in the API Console, which encodes the `+` to `%2B` instead of `%20` or leaving it as is. I'll follow up with a fix or a change in the documentation.

A request to https://api.spotify.com/v1/search?q=album:gold+artist:abba&type=album returns the expected response, and https://api.spotify.com/v1/search?q=album:gold%20artist:abba&type=album as well. (The browser will treat the `+` as a space.)

**Comment by aeikenberry** [comment]
Great. Yeah, I was able to get it to work in my code later. Definitely an encoding issue.

**Comment by thelinmichael** [comment]
@aeikenberry, given that the documentation is reflecting the proper way to separate key/value-pairs in the `q` query parameter (using `%20`), do you mind if this issue is closed?

**Comment by aeikenberry** [comment]
Nope, sounds good! Thanks for the help.
