### ISSUE TITLE
Create a Playlist within a Folder

### ISSUE THREAD

**Issue by stereosupersonic** [spotify/web-api#93]
i would be nice when you create a new playlist, the api accepts a folder as part of the name like "new_stuff/mylist". It should create the playlist 'mylist' in the folder 'new_stuff'. When the folder not exists, the folder should be created.

Thx!

**Comment by thelinmichael** [comment]
Hey @stereosupersonic! As I'm sure you've noticed, the Web API doesn't expose folders in any way right now, and there are no short-term plans on adding it. I'll of course add this as a feature request. Related: See what folder a playlist is in (#38)

**Comment by whyhellothere** [comment]
I second @stereosupersonic need for folders. 

I use the Sonos app and they no longer support folders because of your API. This means that my 800+ folders are a long list and crashes about mid way through scrolling. 

I don't understand why this feature was removed. To be more like Rdio? 

I've spoke with @SpotifyCares, @Spotify, @Sonos and have created these issues: 
https://en.community.sonos.com/music-services-and-sources-228994/spotify-folders-gone-ios-v54-and-v55-6732153

https://community.spotify.com/t5/Help-Other-Partners-Windows/Sonos-Controller-v5-5-no-more-folders/m-p/1219871

**Comment by thelinmichael** [comment]
I've mentioned this in #38 already, but for the sake of visibility I'll add [a link to the Spotify Community Idea post regarding folders in Sonos](https://community.spotify.com/t5/Live-Ideas/Sonos-Playlists-Restore-the-folder-structure-in-the-web-API-so/idi-p/1223003) in this issue ticket as well.

**Comment by MusicPartner** [comment]
I second this also. We are a professional background Music provider and are creating new services using Spotify (and more business for Spotify) so this really needs to get sorted!

**Comment by mrupp12bit** [comment]
YES, me too. Users of my app (iTunes2Spotify, see http://itunes2spotify.mrupp.ch) keep asking me, why folders are not supported and I always have to tell them that it's because of the API missing that feature. PLEASE add this to the API...

**Comment by arirawr** [comment]
Hi all, as per my comment in #38, we have looked into this feature request and we are not able to support playlist folders in the Web API.

Thank you for your patience. We will try to be more clear about things like this in the future.

**Comment by joshcomley** [comment]
Are we still sticking with the `wontfix` tag here?
