### ISSUE TITLE
Recently Played Songs - Not Going to Requested Date

### ISSUE THREAD

**Issue by natxc** [spotify/web-api#965]
I used the 'Get the Current User's Recently Played Tracks' program in the web console - [(https://developer.spotify.com/console/get-recently-played/)]
 I ran it for the date of 07/24/2018 using the correct unix timestamp in milliseconds but every time I do that it will just give me today's songs.

Pplease help! I need the list of songs I listened to on that date.

**Comment by jscholes** [comment]
As per the [docs for this endpoint](https://developer.spotify.com/documentation/web-api/reference/player/get-recently-played/), it's not intended as a general retrieval method for your playback history.  It can return, at most, 50 of your most recently-played tracks.  If you've listened to 50 tracks since the 24th of July, this endpoint cannot be used to determine what you listened to on that date.

**Comment by arirawr** [comment]
Hey @natxc - as mentioned above, this is the intended behaviour of the endpoint. You can only retrieve the 50 most recently played songs, regardless of the date they were played.
