### ISSUE TITLE
Add lyrics information to the response for the tracks endpoints

### ISSUE THREAD

**Issue by ItsPugle** [spotify/web-api#967]
Hey,

I personally think it'd be really good if we were able to see if there are any Genius lyrics associated with a Spotify track through having the responses from the tracks API endpoints include rather a `false` response or the Genius URL.

For example, I help out over at the [Spotify Community](https://community.spotify.com) and when I help users with Lyrics questions I'm not sure if there are lyrics associated with the tracks they're referencing.

**Comment by bih** [comment]
Hello @ItsPugle,

**Comment by bih** [comment]
Hello @ItsPugle,

Thanks for the feature request! I do think there's value in having such an endpoint, but it's worth noting that [Genius have an API](https://genius.com/developers) and that we'd need to spend time obtaining licenses in order to re-distribute Genius annotations and lyrics in general. You can just use the Spotify API and the Genius API together.

For those reasons, we'll not consider this for the next 6 months. Of course, we're happy to reconsider if you have more information or potential use cases to share.

Hope this clears things up. Thank you once again! 👍

**Comment by bih** [comment]
@ItsPugle I think that's a different feature from having Genius lyrics and/or annotations inside of our API itself. Feel free to create a new request mentioning having Genius reference IDs / etc and we can investigate 🙂

**Comment by ItsPugle** [comment]
Ah, sorry @bih. I'll write up a new Issue now 😄
