### ISSUE TITLE
Get a List of Current User's Playlists does not return description

### ISSUE THREAD

**Issue by wdehoog** [spotify/web-api#968]
Issue found on July29th 2018.

#### Endpoint(s):
https://api.spotify.com/v1/me/playlists

#### Scope(s):
playlist-read-private

#### Expected behaviour:
Returned playlists should also contain description field

#### Actual behaviour:
it does not

**Comment by arirawr** [comment]
Hey @wdehoog! This endpoint returns "simplified" playlist objects, which do not include description, as opposed to the "full" playlist object, which do. (You can see both in the Object Model here: https://developer.spotify.com/documentation/web-api/reference/object-model/)

This is expected behaviour for the endpoint. Would you like me to mark this as a suggestion to have this return full playlist objects instead?

**Comment by wdehoog** [comment]
Please mark this as a suggestion. It would make developping easier if you only have to query once.

**Comment by arirawr** [comment]
Hey @wdehoog, thanks for the suggestion.

We've reviewed this suggestion and have decided not to implement it. We return simplified objects for many similar endpoints in order to reduce response size, and don't have any plans to modify that behaviour.

I'm going to go ahead and close this as `wontfix`.
