### ISSUE TITLE
API for getting list of users who follow a specific artist

### ISSUE THREAD

**Issue by knrs** [spotify/web-api#98]
Feature request ..

I'd like to have the possibility to get an artist's followers/listeners who are the logged on user's friends through the API. 

In other words: I want to know which users who I follow, are following a specific artist. 

Would be great if this comes on the todo list :-)

**Comment by thelinmichael** [comment]
Thanks @knrs. I think this fully or partially feature request is covered by #4 (List of Artists & Users a user follows), since that will enable your application to get the current/authenticated user's followed users. That feature request would also enable your application to retrieve the list of artists those users are following. 

If you'd need an endpoint to get an artist's followers, then that'd be a new endpoint and could be the tracked in this Github issue. 

There are some endpoints that are related to this but that doesn't necessarily help your use case, 
- [Check if Current User Follows Artists or Users](https://developer.spotify.com/web-api/check-current-user-follows/)
- [Check Current User's Followed Artists](https://developer.spotify.com/web-api/get-followed-artists/)

**Comment by knrs** [comment]
Thanks @thelinmichael - I will folow #4 for updates about this :-)

**Comment by thelinmichael** [comment]
Cool! I'll close this one then.

**Comment by danilocecilia** [comment]
Thank you!!!

**Comment by ehamiter** [comment]
@thelinmichael --

> If you'd need an endpoint to get an artist's followers, then that'd be a new endpoint and could be the tracked in this Github issue

I would like to request this-- should a new issue be opened?

**Comment by thelinmichael** [comment]
@ehamiter, thanks for the feedback - let's reopen this issue.

**Comment by bih** [comment]
Hello @knrs and @ehamiter,

We're in the process of revisiting all of our Web API issues as [per our new developer support process](https://github.com/spotify/web-api), and given we have no plans to prioritise this suggestion in the next 6 months, we will close this ticket as per our process.

Of course, if you have any additional cases and/or ideas to share, feel free to comment on this issue. We will post here if there are any updates relating to being able to view an artist's followers!
